### ISSUE TITLE
Application specific outgoing https header

### ISSUE THREAD

**Issue by mike00151** [cloudfoundry/gorouter#101]
Hello all

I was wondering if there is a way to add custom https header according to different DEA runtime/application ?

For example : 

Application send https request from cloudfoundry runtime to my service.

The router could automatically add a custom header "XXX-HEADER : FROM USER1"  when the request pass through.

**Comment by shalako** [comment]
Hello @mike00151,

Before we discuss solutions, please clarify your use case. You suggested a client app is running on CF ( ("from cloudfoundry runtime"), sends request to your service. What is your service? Is it also running on CF as an app, or running outside CF? What information does your service need, why, and in what format (does it have to be a header)?

When you say "custom header", what do you imagine is the user experience for how this header is defined? If it can be anything, who chooses what it is? For example, do you imagine a user requesting that all outbound requests made by their app have some header appended? Why not just code the app to do this?

Note: requests from apps on CF to destinations outside CF do not transit the CF routing tier. They go directly from the container host to the network gateway.

Any more information you can provided is appreciated.
Thank you,
Shannon

**Comment by shalako** [comment]
Hello @mike00151 
As we haven't heard back from you, we'll close this issue. 

I recommend using an API gateway to add the header for your application; take a look at http://docs.cloudfoundry.org/services/route-services.html to see how you could add an API gateway in front of your app.
