### ISSUE TITLE
Data race running gorouter

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/gorouter#103]
Running tests caught the following:

==================
WARNING: DATA RACE
Write by goroutine 15:
  github.com/cloudfoundry-incubator/routing-api.(*client).SetToken()
      /Users/fraenkel/t/src/github.com/cloudfoundry-incubator/routing-api/client.go:48 +0x33
  github.com/cloudfoundry/gorouter/route_fetcher.(*RouteFetcher).FetchRoutes()
      /Users/fraenkel/t/src/github.com/cloudfoundry/gorouter/route_fetcher/route_fetcher.go:114 +0x125
  github.com/cloudfoundry/gorouter/route_fetcher.(*RouteFetcher).StartFetchCycle.func1()
      /Users/fraenkel/t/src/github.com/cloudfoundry/gorouter/route_fetcher/route_fetcher.go:47 +0x8f

Previous write by goroutine 16:
  github.com/cloudfoundry-incubator/routing-api.(*client).SetToken()
      /Users/fraenkel/t/src/github.com/cloudfoundry-incubator/routing-api/client.go:48 +0x33
  github.com/cloudfoundry/gorouter/route_fetcher.(*RouteFetcher).subscribeToEvents()
      /Users/fraenkel/t/src/github.com/cloudfoundry/gorouter/route_fetcher/route_fetcher.go:72 +0x18c
  github.com/cloudfoundry/gorouter/route_fetcher.(*RouteFetcher).StartEventCycle.func1()
      /Users/fraenkel/t/src/github.com/cloudfoundry/gorouter/route_fetcher/route_fetcher.go:60 +0x2e

**Comment by shalako** [comment]
Hi, @fraenkel could you provide config used to run the tests so we can reproduce? Errand or manual? Manifest or config file snippets would be helpful.

Thank you

**Comment by fraenkel** [comment]
just ran scripts/test with go 1.5.1
See https://travis-ci.org/cloudfoundry/gorouter/jobs/92951383

**Comment by shalako** [comment]
Pulling this in and calling it a chore as there doesn't appear to be any user-facing changes.

**Comment by shalako** [comment]
Closing as this was fixed.
