### ISSUE TITLE
Collecting infrastructure access log records

### ISSUE THREAD

**Issue by stoyanr** [cloudfoundry/gorouter#105]
Hi,

We would like to be able to collect the access log records of the infrastructure components into our ELK stack. Currently this is not possible. As can be seen in https://github.com/cloudfoundry/gorouter/blob/68aff9a593eb565cef23906cb8c678189de6b9d1/access_log/create_running_access_logger.go and https://github.com/cloudfoundry/gorouter/blob/68aff9a593eb565cef23906cb8c678189de6b9d1/access_log/file_and_loggregator_access_logger.go:

* the access log records are written to a file, if a file is specified in config/gorouter.yml ("access_log").
* the access log records are also sent via dropsonde, but only if the app_id is non-empty

Therefore, infrastructure access log records (with empty app_id) are not sent anywhere besides the file.

One idea how to achieve this would be to add a new (optional) entry in config/gorouter.yml for these log records, e.g. `infra_access_log: <%= p("router.infra_access_log") %>`. If this entry is present, log records with empty app_id are sent in addition to a different file (if specified) or to stdout (if a file is not specified). From stdout, they are sent to syslog via the log capture mechanism in common/utils.sh, and can be collected from there.

Does this make sense? Would you accept a pull request with such a change?

**Comment by stoyanr** [comment]
I submitted a new pull request for this issue, [PR #108](https://github.com/cloudfoundry/gorouter/pull/108). Instead of the proposal above, we thought it would be better to introduce general support for sending access log records with empty app_id to the syslog. For details, see the description in the pull request itself.

**Comment by shalako** [comment]
Closing in favor of #108
