### ISSUE TITLE
Route lookup not working for HTTP requests in absolute-form

### ISSUE THREAD

**Issue by krumts** [cloudfoundry/gorouter#106]
We faced an issue with certain HTTP clients talking to CF, which sent requests with a request target in absolute-form. While this form is meant to be used when talking to proxies, if I understand the spec (https://tools.ietf.org/html/rfc7230#section-5.3.2) properly, the servers also must support it.

Here is an example:
```
GET http://my.test.io/my-path HTTP/1.1
Host: my.test.io
```
results in "404 Not Found: Requested route ('my.test.io') does not exist." in a setup in which the following would work.
```
GET /my-path HTTP/1.1
Host: my.test.io
```

The issue seems to be in the lookup() func in proxy.go, where host and requestURI get concatenated. In the case described above this would result in a lookup for the first two parts of something like my.test.iohttp://my.test.io/my-path

This may be a rather rare case, still I'd like to provide a patch in case you also see it as an issue. I'll submit a PR, which you can review.

**Comment by krumts** [comment]
I created PR https://github.com/cloudfoundry/gorouter/pull/107, let me know if the test/fix are reasonable.

**Comment by shalako** [comment]
Hello @krumts 

Thank you for your contribution. 

RFC-2616 specifies that when an absolute URI is sent, the Host header should be ignored. See https://www.ietf.org/rfc/rfc2616.txt, Section 5.2:

```
An origin server that does differentiate resources based on the host
   requested (sometimes referred to as virtual hosts or vanity host
   names) MUST use the following rules for determining the requested
   resource on an HTTP/1.1 request:

   1. If Request-URI is an absoluteURI, the host is part of the
     Request-URI. Any Host header field value in the request MUST be
     ignored.
```

The Golang HTTP library implements this specification and Gorouter uses the Golang library.  

I'll close this issue and your PR for now; please feel free to reply.

**Comment by krumts** [comment]
Hello @shalako 

Thank you for looking into the issue / PR.
I still think there is an issue, sorry that I didn't describe it detailed enough. I'll give it another try.
I didn't mean that the host is taken from the wrong place (header vs. request URI). There I also would rely on the Golang HTTP lib to do the right job. The issue which I see is that if the request has request-URI in an absolute form, then the lookup which the gorouter makes to find the target is wrong.
The following code
https://github.com/cloudfoundry/gorouter/blob/master/proxy/proxy.go#L127-L130
```
func (p *proxy) lookup(request *http.Request) *route.Pool {
	uri := route.Uri(hostWithoutPort(request) + request.RequestURI)
	return p.registry.Lookup(uri)
}
```
simply concatenates host (taken from the requestURI) and requestUri (the complete URI), which in the case of `GET http://my.test.io/my-path HTTP/1.1` will resilt in a lookup for `my.test.iohttp://my.test.io/my-path`. Some parts of this are cut later in another func, but still with an incorrect result.
Furthemore, the error message which is logged in request_handler.go / HandleMissingRoute() prints only the (correct) request.host, and not the string which was actually used for the lookup.
https://github.com/cloudfoundry/gorouter/blob/master/proxy/request_handler.go#L85

We spent quite some time looking at the registered routes and wondering why the router complains that a route for host xyz is not found, although we see it in the list.

Does this explain the issue better? If you also see it as an issue, please let me know if the proposed fix is ok, or if I should try to fix it in a different way. The test in the PR is reproducing the behavior I described above.

**Comment by shalako** [comment]
Yes, thank you. Now it makes sense. We may have a bug in the lookup. I'll reopen your PR for review.
