### ISSUE TITLE
Allow listening on a unix socket

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/gorouter#110]
Currently gorouter can only listen over TCP. We'd like to have the ability to listen on a local unix socket, to better fit our current setup.

Ideally it would be good to have a generic way to specify one or more ports/sockets for HTTP and zero or more for HTTPS.

**Comment by shalako** [comment]
Hello @CAFxX, could you please explain your use cases? Thank you.

**Comment by CAFxX** [comment]
@shalako sure: for design/compliance reasons we have a reverse proxy (nginx) colocated with the gorouter. Because in our experience sockets are slightly faster having support for them in gorouter would help lessen the latency overhead imposed by the reverse proxy.

**Comment by shalako** [comment]
Sorry for this belated reply. Soon we're going to investigate whether colocating HAProxy with Gorouter would be a more performant solution for terminating TLS than Gorouter alone. To accomplish this, we'll consider having gorouter listen on a socket. 

If we choose not to do that (we may also explore the supposed performance improvements with encryption in golang 1.6; maybe haproxy isn't needed for TLS termination), we'll revisit this request. Sound ok?

**Comment by CAFxX** [comment]
Sure. We can even give it a go if you guys want.

**Comment by shalako** [comment]
We'd welcome a contribution, but let's hash out what the acceptance criteria would be.

If we can assume that access to the VM is secure, then it seems like we only need to enable the http server via socket (not the https server). Does that meet your needs? 

For the same reason, what would be the implications of listening on the socket all the time vs. supporting a manifest property to turn it on?

Thank you.

**Comment by CAFxX** [comment]
> If we can assume that access to the VM is secure, then it seems like we only need to enable the http server via socket (not the https server). Does that meet your needs?

Yes, HTTP-only should be fine for now (the h2/h2c issue might require revisiting this later on)

> For the same reason, what would be the implications of listening on the socket all the time vs. supporting a manifest property to turn it on?

It was my intention (sorry for not making it clearer) for it to be opt-in via the manifest.

To sum it up, the criteria could be "implement an opt-in HTTP-only unix socket listener".

Either as part of this or as a followup I'd suggest refactoring the HTTP and HTTPS listeners because they share most of the code: once this is done, I'd allow in the manifest to specify an arbitrary (>1) number of listeners, e.g. something like:

```
listeners:
  http:
    - "tcp:10.1.1.1:80"
    - "tcp:10.1.2.1:80"
    - "unix:/var/vcap/sys/run/gorouter/listen.sock"
   https:
    - "tcp:10.1.1.1:443"
    - "tcp:10.1.2.1:443"
```

Some deployments (e.g. ours) have multiple network interfaces on the routers; being able to specify which interfaces to use is handy. There could be also performance wins to be gained by allowing multiple listeners - but I haven't benchmarked yet so I can't say for sure it would help.

**Comment by shalako** [comment]
What is the benefit of a server listening on multiple interfaces? Do you have load balancers in multiple networks forwarding requests to the same routers? Do you have different domains resolving to them?

**Comment by CAFxX** [comment]
In our case, it's a security requirement. We have traffic coming in from multiple networks, each network having its own LB. Eventually we'll also have different domains being served on different LBs (that's why we have a reverse proxy in front of the gorouter: knowing which LB the connection comes from lets us enforce which domains can be served).

**Comment by shalako** [comment]
Under what circumstances would you want to the https server to listen on different interfaces than the http server?

**Comment by CAFxX** [comment]
I can't think of a good reason right now, but I'm unsure I understood your question correctly... my example above does not use different network interfaces for http and https, just different ports (if we exclude the unix socket being the goal of this feature request).

**Comment by shalako** [comment]
Hello @CAFxX 
Very sorry for the belated reply; the time just slipped by.

Your proposal sounds reasonable. I'll move the story linked above into the backlog for review by our team.

**Comment by shalako** [comment]
@CAFxX Sorry for the belated reply, the time slipped by so quickly.

I'll move this story into our backlog to give our team a chance to provide design/implementation feedback. We'll reach out when you can begin implementing your PR.

**Comment by atulkc** [comment]
@shalako and @CAFxX 
We discussed this internally within team and we explored a couple of options:

1) One option to achieve supporting unix socket is as follows:
   Use `net.http.fcgi` package in golang, which takes in a `net.Listener` (can be a unix domain socket listener) and `http.Handler` and serves the http request over unix domain socket. In `router.go#Run` method you can do following:

```go
go func() {
        unix, err := net.Listen("unix", SOCK)
        if err != nil {
            log.Fatal(err)
        }
        // handler is the instance of gorouterHandler
        err = fcgi.Serve(unix, handler)
        if err != nil {
            log.Fatal(err)
        }        
    }()
```
   - You will need to use fastcgi client to talk to unix domain socket. It expects some headers to be sent which are specific to fastcgi and in addition to the HTTP headers (imagine that http request is encapsulated in fcgi request)
   - Based on the discussion in github issue it appears that user is interested in running nginx alongside gorouter. nginx  supports fastcgi as backend so it could frontend a tcp port and proxy the requests to backend unix domain socket.

2) Second option is to just create a unix domain socket listener and implement the logic to accept the incoming request and marshal it into `http.Request` and create `http.ResponseWriter` implementation that gets the response from `http.Handler` and writes it back to unix domain socket.

We recommend option 2 primarily to avoid the overhead of `fastcgi`.

Regards,
@atulkc and @markstgodard 
(CF Routing team)

**Comment by shalako** [comment]
Hello @CAFxX,

Let us know if you have any thoughts in response to @atulkc 's comments on implementation above.

Thank you!

**Comment by CAFxX** [comment]
Sorry for the delay in my reply!

Option 2 sounds the better option to me: less dependencies and would arguably better fit in with the current implementation. If we agree on this, will put it in our backlog and see when we can work on it.

**Comment by CAFxX** [comment]
@shalako I opened #142. Turns out it's likely even simpler than option 2, because net.Listen abstracts everything for us (https://golang.org/pkg/net/#Listen). Feedback is welcome.

**Comment by swetharepakula** [comment]
Closing this since the pull request has been created: https://github.com/cloudfoundry/gorouter/pull/142.
