### ISSUE TITLE
CF allows you to map routes which are too large

### ISSUE THREAD

**Issue by Rylon** [cloudfoundry/gorouter#114]
Hi,

We experienced an issue today wherein a user had created an application with a name longer than the limits described in [RFC 1035](http://www.ietf.org/rfc/rfc1035.txt). The RFC describes the maximum length of a fully qualified hostname to be 255 characters, with a limit of 64 characters per label.

If you try to use a route created which exceeds this limit, `curl` and `dig` will be unable to complete the request:

```
$ curl -vi http://this_is_a_really_really_really_really_really_really_long_hostname.yourdomain.com
* Could not resolve host: this_is_a_really_really_really_really_really_really_long_hostname.yourdomain.com
* Closing connection 0

$ dig this_is_a_really_really_really_really_really_really_long_hostname.yourdomain.com
dig: 'this_is_a_really_really_really_really_really_really_long_hostname.yourdomain.com' is not a legal name (label too long)
```

Perhaps the CF CLI should refuse to create and map routes which exceed this limit, instead returning a helpful error message to the user?

Thanks,
Ryan

**Comment by ishustava** [comment]
Hi @Rylon,

Thanks for pointing this out to us. I have moved this issue to Cloud Controller as it is an issue with CC API and not the GoRouter.

@ishustava, CF Routing Team

**Comment by Rylon** [comment]
@ishustava Oops, sorry for placing it in the wrong location, thanks for moving it for me 👍
