### ISSUE TITLE
gorouter cannot handle high amount of requests per second

### ISSUE THREAD

**Issue by milkotodorov** [cloudfoundry/gorouter#115]
Hello,

I cannot manage to make the gorouter handle more than 300 req/sec. I've deployed an simple servlet app on a local CF installation and quering directly the runner I can achieve about 4000 req/sec (each one is very small - about 1K). I've traced that the bottleneck is exactly the gorouter. I've tried some kernel turnings like tcp.ipv4.tcp_tw_reuse=1 even the tcp.ipv4.tcp_tw_recycle=1 as I saw many connections in TIME_WAIT on the router VM, but this doesn't helped. Only the tcp.ipv4.tcp_tw_recycle=1 helped to reduce the TIME_WAIT connections. However this doesn't improved the req/sec. With tcp.ipv4.tcp_tw_recycle=0 I can see that there is up to 16,400 connections in TIME_WAIT, but there are still more available. I appreciate some advice.

Thanks!

**Comment by milkotodorov** [comment]
[pprof_connections_delay.pb.gz](https://github.com/cloudfoundry/gorouter/files/142659/pprof_connections_delay.pb.gz)


pprof / connection_delay

7.47days of 7.47days total (  100%)
Dropped 172 nodes (cum <= 0.04days)
Showing top 10 nodes out of 19 (cum >= 6.18days)
      flat  flat%   sum%        cum   cum%
  7.24days 96.98% 96.98%   7.24days 96.98%  sync.(*Mutex).Lock
  0.11days  1.49% 98.47%   0.11days  1.49%  runtime.selectgo
  0.07days  0.93% 99.40%   0.07days  0.93%  runtime.chanrecv1
  0.04days  0.59%   100%   0.04days  0.59%  runtime.chanrecv2
         0     0%   100%   7.25days 97.10%  github.com/cloudfoundry/dropsonde/instrumented_handler.(*instrumentedHandler).ServeHTTP
         0     0%   100%   1.08days 14.41%  github.com/cloudfoundry/gorouter/proxy.(*BackendRoundTripper).RoundTrip
         0     0%   100%   1.06days 14.16%  github.com/cloudfoundry/gorouter/proxy.(*BackendRoundTripper).selectEndpoint
         0     0%   100%   7.25days 97.10%  github.com/cloudfoundry/gorouter/proxy.(*proxy).ServeHTTP
         0     0%   100%   1.06days 14.16%  github.com/cloudfoundry/gorouter/proxy.(*wrappedIterator).Next
         0     0%   100%   6.18days 82.69%  github.com/cloudfoundry/gorouter/proxy.NewRequestHandler

**Comment by milkotodorov** [comment]
pprof / CPU

69.83s of 166.44s total (41.96%)
Dropped 757 nodes (cum <= 0.83s)
Showing top 10 nodes out of 286 (cum >= 2.51s)
      flat  flat%   sum%        cum   cum%
    17.37s 10.44% 10.44%     18.68s 11.22%  syscall.Syscall
    10.84s  6.51% 16.95%     10.84s  6.51%  runtime.futex
     9.12s  5.48% 22.43%      9.65s  5.80%  syscall.Syscall6
     7.33s  4.40% 26.83%      7.33s  4.40%  runtime.usleep
     5.73s  3.44% 30.28%      5.73s  3.44%  runtime.epollwait
     5.46s  3.28% 33.56%     14.36s  8.63%  runtime.mallocgc
     4.99s  3.00% 36.55%      7.20s  4.33%  runtime.scanobject
     3.64s  2.19% 38.74%      3.64s  2.19%  runtime.readvarint
     2.84s  1.71% 40.45%      2.87s  1.72%  runtime.heapBitsSetType
     2.51s  1.51% 41.96%      2.51s  1.51%  runtime.xchg
[pprof_cpu.pb.gz](https://github.com/cloudfoundry/gorouter/files/142672/pprof_cpu.pb.gz)

**Comment by milkotodorov** [comment]
Graphics shows requests per second (each request is 1024 bytes)

![download](https://cloud.githubusercontent.com/assets/14890886/13253624/31805e78-da3d-11e5-8592-c822ef2a98d1.png)

**Comment by crhino** [comment]
Hi @milkotodorov,

That information is very interesting, thanks for providing it! If you could give us more information about your deployment, specifically what the specs for the gorouter's VM are, that would be helpful. Is the VM's CPU saturated or is it some other issue?

The gorouter will set a number of the kernel parameters you mention [here](https://github.com/cloudfoundry/cf-release/blob/develop/jobs/gorouter/templates/gorouter_ctl.erb#L24-L46), but notably we changed the `tcp_tw_recycle` value [here](https://github.com/cloudfoundry/cf-release/commit/3fe391eac5ce7a3207873dcbe6c1fdf6e642782d) to 0 because of dropped packets.

We definitely want to improve the GoRouter's performance profile, and are scheduled to start a performance-related track of work with the goal of being able to accurately and automatically measure the performance of the router while we develop and eventually improve the performance.

A question I would ask is are you running into issues in a production environment or is this internal load testing? Solving the production environment issue fast can be accomplished by scaling the GoRouter horizontally.

**Comment by milkotodorov** [comment]
Hi @crhino 

by the way this can be tested with a local gorouter and gnatsd. If you send requests with apache benchmark to a fake url like fake.vcap.me:8081 you get a similar results. However if you forward them to a local nginx httpserver you will get much less than the fake and at least 10 times less than forward them directly to the nginx httpserver. I do not give you the numbers as I'm running this on a local VM with ubuntu, but I can notice the difference between how many requests the gorouter can reject and can process. And with my local nginx httpserver I get about 16000 requests per second when I directly query it. 

I think this is an easy reproducible example. Do you have some design documents for the router that I can look at?

Thanks,
Milko

**Comment by crhino** [comment]
Hi @milkotodorov,

The GoRouter README and [this docs page](https://docs.cloudfoundry.org/concepts/architecture/router.html) are the closest to design docs that I could find quickly. I do not believe there are any docs talking in-depth about the GoRouter implementation however, which is definitely something we can improve.

We haven't had time yet to review all the data you have provided, but we will get this issue prioritized and hopefully take an in-depth look soon. Thanks for digging into this as much as you have, anymore information that you find out would be valuable.

@crhino && @shashwathi

**Comment by milkotodorov** [comment]
Hi @crhino 

thanks for looking into this and let me know if you need something or if I can contribute additionally somehow.

Regards,
Milko

**Comment by milkotodorov** [comment]
hi @crhino,

I've found more detailed information about the issue, but I think it is better to close this one and summarize it in another as here is too much information which is now irrelevant. 

Regards,
Milko

**Comment by gsmachado** [comment]
@milkotodorov: did you manage to create another issue about GoRouter's performance? I could not find it, actually. Just because I'm interested about an eventual follow up on that.

**Comment by milkotodorov** [comment]
Hi, yes I already did long time ago. There is already a fix for this even: https://github.com/cloudfoundry/gorouter/issues/119
