### ISSUE TITLE
Gorouter set Content-Type to "" if content-type was not set by backend

### ISSUE THREAD

**Issue by boebu** [cloudfoundry/gorouter#116]
Hi,

According to this change https://github.com/cloudfoundry/gorouter/commit/0d18b57a460b53bcdc46361ac7c41fbb85a92839 the gorouter always sets a content-type even if content-type was not set by the backend. (i.e 204 responses from the CC)

I'd recommend not to set a (invalid) content-type if the backend doesn't provide one.  

any thoughts on this?

BR
Boban

**Comment by atulkc** [comment]
I don't think the change you are pointing to is always setting the content-type header. The change is to check if content-type header is not set by backend then explicitly set the content-type header to null to prevent `go` from guessing the content-type and adding it. So infact this change is doing exactly what you are looking for.

**Comment by shalako** [comment]
The behavior you're asking for was address for #62 and I believe was shipped with cf-release v231. Please let us know if it is not behaving as expected. Closing for now. Thank you!

**Comment by boebu** [comment]
Let me give you an example: (reflects a cfv231 installation):

Request Response from CC before hitting the gorouter:
```
HTTP/1.1 204 No Content
Server: nginx
Date: Sun, 28 Feb 2016 17:49:43 GMT
Connection: close
X-VCAP-Request-ID: 08324651-ead1-4e46-7024-d250ca357105::4b1c2753-740f-4387-9ba4-547f09169bf8
X-Content-Type-Options: no sniff
```

Request Response after hitting the gorouter:
```
HTTP/1.1 204 No Content
Content-Type:
Date: Sun, 28 Feb 2016 17:49:43 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: dda9550e-0c33-4439-7cab-46193ce5b501
X-Vcap-Request-Id: 08324651-ead1-4e46-7024-d250ca357105::4b1c2753-740f-4387-9ba4-547f09169bf8
```

i.e. to gorouter adds an empty content-type even if there was no content-type set before!
And for me this should not be like that.

can easily be verified with cf delete <app> and tracing on the gorouter.

**Comment by markstgodard** [comment]
@shalako, @atulkc 

Hi Shannon

Re-opening this issue for discussion, as technically the fix we added for https://github.com/cloudfoundry/gorouter/issues/116 does not handle the case for HTTP 204 - No Content responses.

We should not nil out / and inadvertently set the Content-Type header for a HTTP 204 response (which should not have a Content-Type header present.

i.e. Current cf v231 will set Content-Type to "", if not set.
```go
if rsp.Header.Get("Content-type") == ""  {
    rsp.Header.Set("Content-type", "")
}
```

What we should change to:
```go
if rsp.Header.Get("Content-type") == "" && rsp.StatusCode != http.StatusNoContent {
    rsp.Header.Set("Content-type", "")
}
```

**Comment by markstgodard** [comment]
@shalako @atulkc 

I tested locally and my suggested changes are here in this branch: https://github.com/cloudfoundry/gorouter/commit/c3134396f933ca8a44d8302fc35f061621d5da31 

We can discuss Monday morning

p.s. I forget cf-gitbot creates a new tracker item when you re-open a GH issue.. we can delete this item if you want:  https://www.pivotaltracker.com/story/show/114641123 and keep this one:  https://www.pivotaltracker.com/story/show/114561395

Cheers

**Comment by fraenkel** [comment]
Hate to say it but "" is an invalid content-type. The values of a content-type must conform to the media-type rule which is token/token.

**Comment by atulkc** [comment]
The reason we set "" as content type if there is no content type set by backend was to avoid implicit content type being set by go lang. Here's the link to golang commit that documents it:
https://github.com/golang/go/commit/5ed44e9d4d06091a9e53128534ce389eb9754e80
So if there isn't a content type header set by backend then the change we did will make sure that golang doesn't implicitly add it. I am not sure why it should be any different for http status code 204.

**Comment by markstgodard** [comment]
@atulkc - re: why different for 204.. looks like Go will only attempt to detect and set the Content-Type for response status types that permit a body.
https://github.com/golang/go/blob/master/src/net/http/server.go#L1027-L1032
https://github.com/golang/go/blob/master/src/net/http/transfer.go#L284

**Comment by atulkc** [comment]
@markstgodard thanks for digging into golang http server code. Based on this code it looks like we need to take care of status codes 204 and 100-199 (for 304 it looks like golang deletes content-type header)  to handle content type being set to empty string.

**Comment by markstgodard** [comment]
@fraenkel - Looking at golang change @atulkc mentioned to suppress content-type from being automatically set:
https://github.com/golang/go/blob/5ed44e9d4d06091a9e53128534ce389eb9754e80/src/net/http/serve_test.go#L1461
it seems like they are setting that header value to nil in the headers map from the response writer and in this test, Content-Type header is not present in the response.  I updated unit tests locally and did similar but did not get the same results ..  so I think we may need to investigate further to see why

@shalako

**Comment by markstgodard** [comment]
@atulkc Yes.

However as per @fraenkel ,  I think we are not suppressing the same way as the golang unit tests. We should expect the response header to not have the Content-Type header vs. right now, where it looks like it present but blank.

We should probably re-open the original #62  issue and dig further

Cheers

**Comment by atulkc** [comment]
@markstgodard it looks for blank because of the behavior of Header.Get behavior 
https://golang.org/pkg/net/http/#Header.Get
It will return blank if no value is associated with that header value.

**Comment by markstgodard** [comment]
@atulkc correct, Header.Get returns "" if not present

So in the unit test: https://github.com/cloudfoundry/gorouter/blob/master/proxy/proxy_test.go#L120

If we check the response by dumping it:

i.e. 
```go
dump, err := httputil.DumpResponse(resp, true)
```

You'll see the Content-Type is still in the response, but its just blank.. when we want it to not be present at all.

```
"HTTP/1.1 200 OK\r\nContent-Type: \r\nDate: Sun, 28 Feb 2016 22:32:06 GMT\r\nContent-Length: 0\r\n\r\n"
```

**Comment by atulkc** [comment]
@markstgodard So 'Header.Get' will not allow us to determine if the header value is not present or present but value is empty string. I guess we should ditch using Header.Get and just use map based lookup (as Header is just a type for 'map[string][]string') to determine presence of header value.

**Comment by markstgodard** [comment]
@atulkc @shalako 

I updated the unit tests and fixed the change to nil out the Content-Type header value using the response writer's header map (similar to how Go 1.5 examples of suppressing) here: https://github.com/cloudfoundry/gorouter/commit/b48b95dae2f1e92eac77425ae8384883cfbaee7a


Before this fix, for responses that did NOT set the Content-Type header, the Content-Type header was being set to blank and being included in the response. (which is not desired behavior) for example:

Given this app that does not set the Content-Type:

```ruby
app = lambda do |env|
  body = "Hello"
  [ 200,
    {
      # OMITTING Content-Type
      "Content-Length" => body.length.to_s,
    },
    [body]
  ]
end
run app
```

The response contains the Content-Type as empty:

```
curl -vvv hello.bosh-lite.com
* Connected to hello.bosh-lite.com (10.244.0.34) port 80 (#0)
> GET / HTTP/1.1
> Host: hello.bosh-lite.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 0
< Content-Type:
< Server: thin
< Set-Cookie: __VCAP_ID__=5936f26ddea84e13b85e5b0e3aab8535543b4605e49f4dd788fc069a10f56775; Path=/; HttpOnly
< Set-Cookie: JSESSIONID=12345
< X-Vcap-Request-Id: 17d4677d-fbac-4527-6593-84072988b568
< Date: Sun, 28 Feb 2016 19:19:24 GMT
<
* Connection #0 to host hello.bosh-lite.com left intact
Hello
```

After this change in my remote branch https://github.com/cloudfoundry/gorouter/commit/b48b95dae2f1e92eac77425ae8384883cfbaee7a , the response looks as follows:

NOTE: That Content-Type header is NOT PRESENT at all, which is the desired behavior.

```
curl -vvv hello.bosh-lite.com
* Rebuilt URL to: hello.bosh-lite.com/
*   Trying 10.244.0.34...
* Connected to hello.bosh-lite.com (10.244.0.34) port 80 (#0)
> GET / HTTP/1.1
> Host: hello.bosh-lite.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 5
< Server: thin
< X-Vcap-Request-Id: e823a16f-d7c6-4280-457d-4f9465220210
< Date: Mon, 29 Feb 2016 15:57:50 GMT
<
* Connection #0 to host hello.bosh-lite.com left intact
Hello
```

cc @fraenkel

**Comment by fraenkel** [comment]
LGTM

**Comment by markstgodard** [comment]
Thanks @boebu , yes this was not correct.. fixed in latest

**Comment by shalako** [comment]
Verified fix on superman environment. 

```
$ curl -v 10.0.32.15 -H "Host: bash-hello.superman.cf-app.com"
* Rebuilt URL to: 10.0.32.15/
* Hostname was NOT found in DNS cache
*   Trying 10.0.32.15...
* Connected to 10.0.32.15 (10.0.32.15) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host: bash-hello.superman.cf-app.com
>
< HTTP/1.1 200 OK
< Content-Length: 1
< X-Vcap-Request-Id: 6d29cdd7-959d-4455-49f5-474a6afc0fd2
< Date: Tue, 08 Mar 2016 01:47:58 GMT
<
* Connection #0 to host 10.0.32.15 left intact
```

The fix should be included in cf-release v232. The bump to gorouter in cf-release has made it to release-candidate: https://github.com/cloudfoundry/cf-release/commit/ef1b5bd5c76adb517e2e567140abc8a26f7ef029
