### ISSUE TITLE
Questions about access logs in stdout

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/gorouter#117]
I recently noticed this commit: https://github.com/cloudfoundry/gorouter/commit/f079b7a64cf35bc3a5b7f5f06f7557b07a951c2a

We may be weird but in my organization we make monitoring data including component logs public to our users.  We recently noticed the access logs of other applications started appearing in our public component logs.  I think some of our users and uncomfortable with other users seeing their application access logs.

That said I also really like this commit because it allows me to see CC and other non application access logs in my central monitoring logs so I'm a little torn on this commit.

At the very least would you consider a config option to turn off sending access logs to stdout?  At the most it would be great if I could continue to get access logs for routes that don't have an app Guid.  But I can see how that may not be gorouters job.

Thoughts?

**Comment by shalako** [comment]
Hi Mike,

I am surprised that you make the logs of CF system components to end users. I haven't heard of that use case before. 

As you're probably aware, we send access logs to stdout because we use lager to stream all logs out over syslog. If we were to add a property, it would be something like `syslog_includes_access_log:true` (open to better suggestion for naming). I'd want the property to control whether access logs were streamed to syslog; the use of stdout and lager is an implementation detail. Make sense?

Could you send us PR for this? 

Thank you

**Comment by youngm** [comment]
@shalako Understood. I'll put together a PR.  Thanks Shannon!

**Comment by youngm** [comment]
@shalako I think I'd be fine for our needs with turning access logs completely off on the gorouter.  Thoughs on simply submitting a PR to allow the `access_log` config to be customized in the release?  Then I can just give it an empty value and disable access logging that way?  Or perhaps you'd prefer an explicit flag to turn off access logging?

**Comment by shalako** [comment]
FYI, the team is digging into our use of lager base on performance reports in #119. There may be some changes in that area of the code as a result. I believe we're still testing at this point.

Please help me understand the difference between a manifest property that can be used to turn off streaming of access log to syslog (you could implement this by turning off sending access log to stdout; I don't care), and your proposal to allow config of `access_log`? Do you mean that access logs would also not be logged locally? ...when on - log locally and stream to syslog via stdout; when off - do neither...

Thank you

**Comment by youngm** [comment]
@shalako  Yes, I was just thinking a config entry to turn off access logs all together might be simpler for users to grok and leave you more flexibility for the the property might morph in the future.  For example, what if in the future instead of sending access logs stdout for syslog the access logs were instead sent through the application logging framework.  A property that simply turns off access logs would still be be workable where as a property that just turns off access logs to syslog may be more difficult to continue supporting.

I started to think that if I simply exposed config.AccessLog in the release I'd only have to set that value to an empty string which would effectively turn off access logging [0].  But I now think that a flag to turn off access logging in general may be more appropriate.

[0] https://github.com/cloudfoundry/gorouter/blob/master/access_log/create_running_access_logger.go#L23

**Comment by shalako** [comment]
I appreciate your thinking about a solution that leaves us the greatest flexibility in the future. To take your example, if I wanted to turn off syslog streaming in the futurem and rely on metron for export, how could I still count on local access logging being active?

**Comment by youngm** [comment]
@shalako Under the enable/disable access logs proposal then the ability to get access logs on the node but not in syslog wouldn't be an option.  Either access logs are logged or they aren't.  Either all router logs (including access logs) go to a drain if enabled or they don't.

For my situation I'm not interested in access logs at all logged by gorouter.  If I want system global access logs I'll make a firehose nozzle and send the access logs I logged sent to syslog.

Either option will accomplish my ultimate goal of not putting access logs in syslog.  Just thought I'd offer the possibility of simply turning off all access logs as a solution before I start implementing either one.

**Comment by shalako** [comment]
> Either all router logs (including access logs) go to a drain if enabled or they don't.

This would remain controlled by `syslog_daemon_config properties`, correct? 

- when `access_logging_enabled:true` access.log would be logged locally
- when `syslog_daemon_config properties` is also configured, access.log (and gorouter.log) would be streamed to syslog

This sounds reasonable.

**Comment by youngm** [comment]
@shalako Yup, that's what I'm thinking.

So my PR will simply add an "access_logging_enabled" config (true by default) which simply turns on or off access logging here: https://github.com/cloudfoundry/gorouter/blob/master/access_log/create_running_access_logger.go#L23

I'll put together that PR.

Thanks,
Mike

**Comment by shalako** [comment]
Closing as streaming of access logs will be disabled in #119
