### ISSUE TITLE
Tracing the http request id across the cf apps

### ISSUE THREAD

**Issue by kishorereflection** [cloudfoundry/gorouter#118]
Hi

Is there a way we can track the http request going from one app to another app. For example in our product  we have multiple services. When a user performs an action in the UI the request goes from cf app A to B the go router generates a new request Id every time it goes to an app. We would like track the initial request originated from the cf app A  when we monitor the cf logs in app B. Ideally if there is a unique request id  for every request originated from user action, it will be very handy for troubleshooting purpose. Let us know if there is another way we can track the requests. Appreciate any help

Thanks
Kishore

**Comment by crhino** [comment]
@kishorereflection That definitely sounds like a valid use case. As you say, the GoRouter does not currently support that type of request tracing, perhaps we could think about doing something to help applications in this area though.

The hard part about handling tracing multiple requests in the GoRouter is that we do not know anything about what requests are related or not. Perhaps having an application-specific header that is passed through by your applications would help enable this type of tracing?

@crhino && @fordaz

**Comment by shalako** [comment]
@kishorereflection Some time ago we merged PR #92 to add generic support for this use case. When deploying cf-release, you may configure a list of headers that gorouter will include in logs if they are present in requests. 

This configuration property is: `router.extra_headers_to_log`

For example, if you configured your BOSH deployment manifest with `router.extra_headers_to_log: ["X-My-Trace-Header"]`, then updated your apps to pass a unique value back and forth for each request, you'd be able to trace request a request across applications.

I'll close this story for now. Please reopen if you have any additional questions.
