### ISSUE TITLE
Proper handling of 502 in GoRouter

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/gorouter#120]
This is a minor issue that you probably won't change, but I thought I'd bring it to your attention anyway.

When the gorouter has an open mid request connection with an application instance and the application crashes.  Today the GoRouter will display a 502 Bad Gateway error page which is fine for the most part.  However, when fronted by an ELB where the enterprise has established standard error page configuration this behavior can circumvents that global error page behavior.

I believe the correct behavior the GoRouter should exhibit in this situation is to drop the connection.  This allows the ELB to handle such a failure the same way it would handle any server it is proxying to crashing or going away.

Granted this isn't a big deal since GoRouter is nice enough to inject a header that an ELB can listen for and rewrite the response, but dropping the connection may provide for a simpler more seemless integration of CF with existing ELBs in enterprises.

GoRouter returned 404s also cause some trouble but I think the correct way to handle a 404 at a higher than layer 4 proxy is less clear and deploying an application that displays a pretty 404 (or 503 if the requested route exists on the CC) with a wildcard route isn't too difficult of a workaround.

**Comment by shalako** [comment]
Thank you for this info @youngm. Your use case seems reasonable and valid at first pass. I've got my hands full at the moment but would like to revisit this at some point. I'm glad there's a workaround. Please let me know if this becomes more of a pain.

**Comment by youngm** [comment]
@shalako ok, feel free to close this if you have a tracker issue for it.  Just wanted this pain point noted before I move on and forget about it.

**Comment by abbyachau** [comment]
We are closing this issue now; please let us know if this becomes more of a problem.
