### ISSUE TITLE
StartedAt logged only with seconds granularity

### ISSUE THREAD

**Issue by MichaelStephan** [cloudfoundry/gorouter#123]
As can be seen in access_log_record.go line 29 the used time output pattern leads to timestamps which only have second granularity. This fact makes the access logs (or RTR messages) less usable as they could be. Would it be possible to also include the milliseconds into the log output? 

Thanks for your feedback.

Cheers,
Michael Stephan (michael.stephan@sap.com)

**Comment by shalako** [comment]
Hello @MichaelStephan thanks for the feedback. Seems like a reasonable request. We'll investigate whether this is an easy change. Moving the review story into the backlog.

**Comment by shalako** [comment]
Hello @MichaelStephan we implemented this in https://github.com/cloudfoundry/gorouter/commit/dab0ce83e6d9fda8b865cffc943ea8f089f4ebc4

This change is included in final release v234 of cf-release
https://github.com/cloudfoundry/cf-release/commit/53306998e51ad051ec013899ba6d5c9ac7f97f45

**Comment by MichaelStephan** [comment]
Hello @shalako, thanks for delivering the solution that fast.
