### ISSUE TITLE
Project is can build ok?

### ISSUE THREAD

**Issue by ghpaas** [cloudfoundry/gorouter#124]
I try many time,and change my golang version 1.4,1.5,but can't build ok,below is my build trance.
root@iZ62fljfnxxZ:~# go get -v github.com/cloudfoundry/gorouter
github.com/cloudfoundry/gorouter/common
# github.com/cloudfoundry/gorouter/common
gorouter/src/github.com/cloudfoundry/gorouter/common/component.go:108: cannot use func literal (type func(*"github.com/apcera/nats".Msg)) as type "github.com/nats-io/nats".MsgHandler in argument to mbusClient.Subscribe
github.com/cloudfoundry/gorouter/route_fetcher
# github.com/cloudfoundry/gorouter/route_fetcher
gorouter/src/github.com/cloudfoundry/gorouter/route_fetcher/route_fetcher.go:27: undefined: db.Route
root@iZ62fljfnxxZ:~#

**Comment by markstgodard** [comment]
Hi @ghpaas 

It looks like the dependencies are not installed.

Make sure GOPATH is set,  godep is installed and you will need to call godep restore to install all of gorouter's dependencies (Godeps.json) into the GOPATH
```
go get -v github.com/tools/godep
godep restore ./...
```
For more information
https://github.com/cloudfoundry/gorouter#external-dependencies

Cheers

**Comment by shalako** [comment]
Closing. @ghpaas Let us know if this continues to be an issue after following @markstgodard 's suggestions.
