### ISSUE TITLE
Job spec and templates reference unused logging properties

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/gorouter#128]
The number of confusing metron/port properties in the different jobs in cf-release was brought up in https://github.com/cloudfoundry/cf-release/issues/956.

One issue highlighted there was that `gorouter` has a legacy property.  It is now safe to get rid of `metron_endpoint.port`:

https://github.com/cloudfoundry/cf-release/blob/75b5699/jobs/gorouter/spec#L126-L128

It is referenced in the job templates for creating the gorouter config YAML:

https://github.com/cloudfoundry/cf-release/blob/75b5699/jobs/gorouter/templates/gorouter.yml.erb#L27-L30

However this section of the YAML is no longer even recognized by the gorouter config struct:

https://github.com/cloudfoundry/gorouter/commit/1913cc5722ac49e19d6e06529fd928701cab294a

That bit of YAML/ERB should removed from the template as well.

**Comment by Amit-PivotalLabs** [comment]
Reading more carefully, @youngm mentioned most of these points already in that other issue.

**Comment by crhino** [comment]
Fixed in story above.
