### ISSUE TITLE
Failover fails with invalid Read on closed Body

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/gorouter#130]
This was reported via slack from rwwohl

HM9000 introduced a bug that exposes a bug in gorouter.
There are 2 HM9000 instances but the bug only allows one API server to respond.

cf apps is reporting ? for all instances when the problem occurs.
The log below shows what is going on.
The first request hits the dial failure which is the HM9000 that is down.
However the second request fails with an invalid Read on closed Body which is not good. It is almost like back end connections are cached and when we reuse them they are stale.

```
"timestamp":"1461784820.664089203","source":"vcap.gorouter","message":"vcap.gorouter.proxy.request-handler.backend-endpoint-failed","log_level":2,"data":{"Host":"hm9000.dd.com","Path":"/bulk_app_state","RemoteAddr":"10.0.1.148:33498","X-Forwarded-For":null,"X-Forwarded-Proto":null,"error":"dial tcp 10.0.20.229:5155: getsockopt: connection refused","session":"4.5365"}}
{"timestamp":"1461784820.665650368","source":"vcap.gorouter","message":"vcap.gorouter.proxy.request-handler.endpoint-failed","log_level":2,"data":{"Host":"hm9000.dd.com","Path":"/bulk_app_state","RemoteAddr":"10.0.1.148:33498","X-Forwarded-For":null,"X-Forwarded-Proto":null,"error":"http: invalid Read on closed Body","route-endpoint":{"ApplicationId":"","Addr":"10.0.16.156:5155","Tags":{"component":"HM9K"},"RouteServiceUrl":""},"session":"4.5365"}}
{"timestamp":"1461784820.665900230","source":"vcap.gorouter","message":"vcap.gorouter.proxy.request-handler.status","log_level":1,"data":{"Host":"hm9000.dd.com","Path":"/bulk_app_state","RemoteAddr":"10.0.1.148:33498","X-Forwarded-For":null,"X-Forwarded-Proto":null,"body":"502 Bad Gateway: Registered endpoint failed to handle the request.","route-endpoint":{"ApplicationId":"","Addr":"10.0.16.156:5155","Tags":{"component":"HM9K"},"RouteServiceUrl":""},"session":"4.5365"}}
```

**Comment by crhino** [comment]
@fraenkel Thanks for the report, looking further into this it seems like we had a bad issue where any non-nil request body was being closed on the first retry attempt, causing subsequent retries to fail and return a 502 response.

To fix this issue, we decided to wrap the request with a no-op Close method when retrying, and ensure that the underlying body is closed after all retries have been attempted.

**Comment by fraenkel** [comment]
Sounds like a bug against Golang. Why should they close the request body when it hasn't been touched. I would recommend you report it and see what they think since it doesn't make sense in all cases.

**Comment by shalako** [comment]
Hello @fraenkel I think we fixed this.

I set up the following test scenario to validate:
- In an environment with 4 cells and two routers
- I stopped one of the routers so I could watch the logs on the other
- I pushed dora and scaled it to two instances
- I used /v2/apps/:guid/stats to find the cells where the instances where running
- on the router I used iptables to drop requests to one of the cells `iptables -A OUTPUT -j DROP -d 10.0.64.70`
- I curled dora with a body `curl dora2.superman.cf-app.com -d '[0]'` and saw in gorouter logs 
  ```
{"timestamp":"1463007754.394642353","source":"vcap.gorouter","message":"vcap.gorouter.proxy.request-handler.backend-endpoint-failed","log_level":2,"data":{"Host":"dora2.superman.cf-app.com","Path":"/","RemoteAddr":"10.0.4.107:41586","X-Forwarded-For":null,"X-Forwarded-Proto":null,"error":"dial tcp 10.0.64.70:60346: i/o timeout","session":"4.128981"}}
  ```
The app responded with a 404 (doesn't have a POST endpoint on `/`)
- This suggests that gorouter attempted to forward the request to `10.0.64.70`, couldn't connect and successfully connected to another backend. Gorouter marks this backend failed for 30s; I don't see gorouter attempt to send requests to that host until after 30s

I'll accept the story and close this issue. If you have a chance please verify the fix using release-candidate or let me know if my validation isn't sufficient.

Thank you

**Comment by fraenkel** [comment]
I also tested with my testcase that uncovered the issue and it works.
