### ISSUE TITLE
X-Forwarded-For Not Passed Through To Apps

### ISSUE THREAD

**Issue by d4v3r** [cloudfoundry/gorouter#133]
I discovered some issues related to the `X-Forwarded-For` header that at least need clarification.

I am using a PCF 1.7 implementation.  HAProxy Load Balancer.

It has always been an understanding of mine that the `X-Forwarded-For` header would be passed to applications running in PCF so that they can identify the requester IP address.  Upon developing a route service I have observed the following behavior.

1 - Applications do not receive the `X-Forwarded-For` header.  They do receive the `X-Forwarded-Proto` header.

2 - The Router seems to be aware of the `X-Forwarded-For` header despite it not being passed through to the application because it logs it, although hyphens have been changed to underscores.  Why underscores?

`2016-05-16T13:44:49.77-0500 [RTR/0]      OUT route-service.cfapps.haas-39.pez.pivotal.io - [16/05/2016:18:44:49.756 +0000] "GET / HTTP/1.1" 200 0 4 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36" 10.65.188.32:52086 x_forwarded_for:"66.68.129.103, 10.65.188.32" x_forwarded_proto:"http" vcap_request_id:ecd2ebde-51f4-4b4f-470d-0d17b0458290 response_time:0.01477425 app_id:285db3c4-11c7-4762-9f95-7ef130da3d9d`

3 - `X-Forwarded-For` is also not passed through to a bound route service.  I was building a rate limiting example based partially on this header and experienced these issues.

**Comment by shalako** [comment]
Hello,
It seems the issue you're having is that X-forwarded-for isn't received by your route service. Is that correct?

Can you confirm that without a bound route service, apps receive this header?

Thank you

**Comment by d4v3r** [comment]
They do not.  That is what I was try to convey in points 1 & 2.

**Comment by kstrini** [comment]
Was this ever cleared up? I have a customer asking for the exact same thing... access to the x-forwarded-for headers in order to identify IP address

**Comment by d4v3r** [comment]
@kstrini not yet to my knowledge.

**Comment by crhino** [comment]
@d4v3r @kstrini What type of app/buildpack are you using? We were able to see applications receive the `X-Forwarded-For` header on the latest cf-release version with a simple golang app.

**Comment by d4v3r** [comment]
@crhino the Java Buildpack with a Spring Boot App.

**Comment by shalako** [comment]
I believe this was resolved through Pivotal support tickets. Apps receive this header just fine. 

Spring Boot apps should not be looking for these headers, as Tomcat turns them into java variables that Spring boot apps can handle natively.

**Comment by jghiloni** [comment]
@shalako as I'm seeing this issue too, can you point to some documentation about what java variables a boot app has access to for the `X-Forwarded-For` header values? Thanks!

**Comment by shalako** [comment]
I don't know but @nebhale would.

**Comment by nebhale** [comment]
@jghiloni these headers are handled by Tomcat's [`RemoteIpValve`](https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve).  Check it's documentation for extra extend behaviors.

**Comment by rahul6941** [comment]
Please let know solution for this one .

**Comment by rahul6941** [comment]
> I believe this was resolved through Pivotal support tickets. Apps receive this header just fine.
> 
> Spring Boot apps should not be looking for these headers, as Tomcat turns them into java variables that Spring boot apps can handle natively.

Please share code for this Java Variables. We are also facing same issue.
