### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by lancecarlson** [cloudfoundry/gorouter#134]
I'm trying to go build on windows and I'm running into issues:

```
go build
# github.com/cloudfoundry/gorouter/access_log
access_log\file_and_loggregator_access_logger.go:62: undefined: syslog.Dial
access_log\file_and_loggregator_access_logger.go:62: undefined: syslog.LOG_INFO
# github.com/cloudfoundry/gorouter/common
common\component.go:58: undefined: syscall.Getrusage
common\component.go:58: undefined: syscall.RUSAGE_SELF
common\component.go:65: p.rusage.Maxrss undefined (type *syscall.Rusage has no field or method Maxrss)
common\component.go:67: p.rusage.Utime undefined (type *syscall.Rusage has no field or method Utime)
common\component.go:67: p.rusage.Stime undefined (type *syscall.Rusage has no field or method Stime)
```

**Comment by shalako** [comment]
Hello @lancecarlson,

Are you attempting to deploy Cloud Foundry to Windows VMs or interested in using Gorouter for another purpose? Although I'm curious about your use case, we've never tried deploying Cloud Foundry on Windows and only have the resources to support deployment via BOSH, using the Ubuntu Trusty and CentOS 7 images listed here: http://bosh.io/stemcells

**Comment by lancecarlson** [comment]
@shalako at this point it's just been for development on my own machine. (I use msys :))

**Comment by markstgodard** [comment]
Unfortunately log/syslog is not implemented in golang for Windows. There is discussion on this thread about it. 
https://golang.org/issue/1108

Gorouter requires a syslog subsystem for the sending access logs to syslog feature.  So unfortunately right now this means it works only on UNIX / Linux based platforms.

@shalako 
We could investigate getting gorouter buildable on Windows and ensure bash scripts work with something like Cygwin or new Windows bash support, however I think it would depend on demand as well most CF dev and CI is Linux or OS X based.

**Comment by crhino** [comment]
Closing this issue, as we do not believe Windows support for GoRouter is particularly valuable. If you have specific reasons why you think we should have Windows support, please reopen and tell us your use case.
