### ISSUE TITLE
404 in case of route not found

### ISSUE THREAD

**Issue by MichaelStephan** [cloudfoundry/gorouter#135]
Hello,

in case I want to access an app which is not registered or which is not running at a certain time the router returns a 404. Unfortunately 404 may also have a business meaning next to the technical issue indicated by the router. Could the cloud foundry router either return 503 (which is a breaking change and therefor I would understand that it cannot simply be done) or indicate with a custom header field that the 404 was returned by the router itself (router error) and no upstream service.

Best regards,
Michael
(michael.stephan@sap.com)

**Comment by crhino** [comment]
Hi @MichaelStephan,

There has been a number of discussion on the mailing list about this topic. In summary, we might consider returning a 503 status code for routes that are registered on Cloud Foundry but do not have any applications currently mapped to them, but that would involve some substantial changes to how routes are registered.

There are a few workarounds that people have come with, see the links below for more details on that and discussion around this issue.

[CF RTR returning 404 when app is down](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/CO6S5HLHQCJRS4ULZUUCFBE5YJRHDAWZ/#DRWZNGR6Q43LSWMORQJ66J25JHGGUYWA)
[How can we customized "404 Not Found"](http://cf-dev.70369.x6.nabble.com/cf-dev-How-can-we-customized-quot-404-Not-Found-quot-td4501.html#a4913)
[Brokered route services only receiving traffic for routes mapped to started apps](http://cf-dev.70369.x6.nabble.com/cf-dev-Brokered-route-services-only-receiving-traffic-for-routes-mapped-to-started-apps-tp4699p4742.html)

**Comment by shashwathi** [comment]
@MichaelStephan : In the description you mentioned custom header field to truly represent `404` returned by the router itself. There is a header field`X-Cf-RouterError` which is set to `unknown_route` by gorouter.

Regards
Shash

**Comment by swetharepakula** [comment]
@MichaelStephan. We are closing this for now due to inactivity. Please let us know if you would like to reopen for further discussion.

Thanks,
@swetharepakula && @aaronshurley

**Comment by Netha6571** [comment]
@MichaelStephan did you get any solution for this problem.
