### ISSUE TITLE
"Development Setup  Option 1: GoRouter (standalone)" in README doesn't work

### ISSUE THREAD

**Issue by tomoe** [cloudfoundry/gorouter#139]
README needs to be updated accordingly because dependencies are not vendored, the code didn't compile. Reported in #routing slack channel:  https://cloudfoundry.slack.com/archives/routing/p1467866936000626

**Comment by crhino** [comment]
@tomoe thanks for the report, we have removed that from the README since we only test using the routing-release as our GOPATH.

**Comment by tomoe** [comment]
@crhino NP. Thanks for the update and just confirmed that the fix has been merged ba35583312e2eaf171805bc3ef40e52756ea6f6e
