### ISSUE TITLE
How to map individual routes to same app multiple instance ?

### ISSUE THREAD

**Issue by pradeepsingh1234** [cloudfoundry/gorouter#149]
I have an application name HelloWorld and scaled over to 4 instances. want to do the health check on the individual instance. Need a way to do this.

**Comment by shalako** [comment]
Gorouter does not do healthchecks itself. Instead, we rely on clients registering their routes repeatedly to keep the route active. If Gorouter does not receive an update for a given route in 120 seconds, the route is removed from the routing table.

The client registering routes should register all instances of any app, and continue registering these routes to keep them in the Gorouter routing table.

If you deployed your app to Cloud Foundry and scaled it to four instances, a component called Route-Emitter that watches the Diego runtime service would discover there are four instances of an application, the IP and ports for these instances, and the route for this app (e.g. `myapp.cf.com`). Route-Emitter sends a registration message to NATS, and Gorouter receives the registration message (it is subscribed to NATS). Requests for `myapp.cf.com` will now be load balanced across the four instances of your application. The Route-Emitter continues to send the registration every 20 seconds, so the application stays available. 

When you scale your application down from 4 to 3 instances, Route Emitter detects that an instance was removed and tells Gorouter, via NATS, with an unregister message. 

Does this answer your question? If you are using Cloud Foundry, this is all taken care of for you automatically. If you are using Gorouter without Cloud Foundry, you could use [Route Registrar](https://github.com/cloudfoundry-incubator/route-registrar) to register your app instances.

Does this answer your question?

**Comment by flaviaBaer** [comment]
Hi, I think @pradeepsingh1234 refers to a feature of Spring Boot Admin we would like to use: https://github.com/codecentric/spring-boot-admin/issues/268#issuecomment-247364016
Spring Boot Admin needs the specific health-url for every instance it has to manage. Is this already possible with https://github.com/cloudfoundry/gorouter/commit/1647c65cf65f712f7597c811cf7f98cfaab9365a ?

**Comment by flaviaBaer** [comment]
Yes I am using CF. When will the feature be included into a release?

**Comment by shalako** [comment]
We should be cutting a final release of routing-release this week. The next cf-release to be cut after than will include the feature. Likely within a few weeks.

**Comment by shashwathi** [comment]
@flaviaBaer @pradeepsingh1234 : 
Closing this issue since this feature is present in CF release and Routing release.

Regards
Shash
