### ISSUE TITLE
Self-signed certificate for uaa communication

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/gorouter#151]
Hi,
I recently tried to deploy the tcp-routing-release and one step of the process is to configure UAA with a certificate. Due to the fact that I have only self signed resources running internally I am getting the following error:

```
Post https://uaa.service.cf.internal:8089/oauth/token: x509: certificate signed by unknown authority
```

My question now: is it possible to specify the acceptance of self-signed certificates, or to use a different port (8080/80) for the communication?

Thanks!

**Comment by shalako** [comment]
Hello,

Set manifest properties `skip_ssl_validation: false` and `router.ssl_skip_validation` to accept self-signed certs.

Let us know if this resolves your issue.

**Comment by jhiemer** [comment]
That worked. Perfect, could not find anything in the docs. Is this a hidden feature?

**Comment by shalako** [comment]
Hello, 
Sorry for the belated reply. 

Skipping TLS validation isn't a hidden feature; just not documented in the README. In general, all configuration options for a BOSH release can be found in the spec files under the `/jobs` directory:
https://github.com/cloudfoundry-incubator/routing-release/tree/develop/jobs

I have added a section to the deploy instructions to document this explicitly:
https://github.com/cloudfoundry-incubator/routing-release/blob/develop/README.md

I'll close this issue now.
