### ISSUE TITLE
Consider sending endpoint failures to application log stream also

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/gorouter#153]
In my gorouter logs I see many messages like the following:

```
{"timestamp":"1476379410.654025555","source":"vcap.gorouter","message":"vcap.gorouter.proxy.request-handler.backend-endpoint-failed","log_level":2,"data":{"Host":"some.host.com","Path":"/client","RemoteAddr":"someip:port","X-Forwarded-For":["someip"],"X-Forwarded-Proto":null,"error":"dial tcp someip:port: i/o timeout","route-endpoint":{"ApplicationId":"appguid","Addr":"someip:port","Tags":{"component":"some dea"},"RouteServiceUrl":""},"session":"4.54820166"}}
```

The way I read this is that the gorouter attempted to send a request to an instance of an app and failed.  In this case because of an i/o timeout.  Probably some issue with the application.

It think it would be useful to send something to the application log stream letting them know that the router failed to route a request to an application instance.

I also understand that gorouter will try a different instance in the case of a failure like this.  If the router is going to try a different instance it would be nice to let to use know in their app log stream.  If it is a final failure we should let them know that too.

I know my users would love to have this information.

Thoughts?

**Comment by shalako** [comment]
Sounds interesting.

What if the reason the router couldn't reach an app instances was not an app problem? Wouldn't this be platform noise for the developer?

**Comment by youngm** [comment]
@shalako Good question.

Let me put some scenarios into 3 categories.  Situations where an app is not working correctly and the app developer could use this log message.  Not normal situations where there is something wrong with CF or a CF deployment causing an app developer to see a message they cannot do anything about. Situations where CF and an app is working as designed, a user would get a message, and the message would be not useful.

Situations useful to the App developer:
* Instance crashed prior to router attempting to connect.
* Instance Crashing mid request.
* Instance dropping a connection.
* App not properly draining requests after receiving sigterm.

Situations of a CF bug or a CF deployment mis-configuration where the developer would get an non actionable message:
* Router has a stale instance in routing table and failing to connect to it.
* Network firewall between router and app instance.
* Flaky network between router and app instance.

Situations where CF and app are working property and message is not actionable:
* Application is purposefully limiting number of concurrent connections and attempting to force router to send request to another instance (I've never seen an app do this on purpose before)

Even in the above situation I think it could still be useful for an app developer to know when requests are rolling to another instance.

Can you think of any scenarios to add to the lists?

You will probably want to log the VCAP_REQUEST_ID or something so when analyzing logs they will be able to track a request as the router rolls the attempt from instance to instance.

Mike

**Comment by shalako** [comment]
There may be one or two scenarios which a developer would be interested in that we could log, but it seems that several of them would be difficult to differentiate with system issues.

**Comment by youngm** [comment]
So, let me restate what I hear you saying.  You are concerned that a CF deployment might be mis configured or not working correctly.  And in this state a user of this system would get noise in their logs that they cannot do anything about, right?

My question back is, why are we concerned about accidentally sending logs to a user when a system is functioning incorrectly?  It seems to me that instead we should be thinking of the value this would provide when the system is working properly since a properly working CF deploying I think should be the expected environment a user would be using.  Does that make sense?

If you can think of a use case where a user would get noise with this feature when the system is working properly then I think that would be a good counter argument.  But saying you are concerned about noise users will get when a system is broken doesn't really make sense to me.  Why cares about bothering a user with log noise when the CF they are using is broken?

Am I making sense?

**Comment by youngm** [comment]
@shalako Or, perhaps you are trying to say that a CF system running normally and configured properly might occasionally get in some state causing a message to be logged that is unactionable by the user?

Even in this scenario I think that I, as a cf app developer, would still like to see that a request to my application was attempted and failed for some reason.  Even if I cannot do anything about it the fact that someone attempted to use my application and failed is something that I, as a cf app developer, would like to be aware of  irregardless of the root cause.

Thoughts?

**Comment by shalako** [comment]
Yes, that was the point I was making. For the sake of discussion we can assume the platform/infra/network are operating correctly. 

The Routing team has suggested that if the router finds a match in the routing table and attempts to connect, it already logs to the access log even if:
- router could not connect to any app instance
- could connect but connection dropped before app responds

The only scenario where the router does not log to access log is when it retries; only the last attempt is logged. e.g. If there are two app instances and router fails to connect to one instance but succeeds in connecting to another, only the success is logged. If it failed to connect to either, an error is logged. In both cases, the developer should see the single log message. 

Does this match your observations? If so, does this suggestion boil down to "log failed connection attempts to access log when there are multiple instances"?

**Comment by youngm** [comment]
@shalako I think the main point of this issue is that I would like to see some routing failures logged to an app's loggregator stream.  Logging this information to the router access log doesn't help my end users.  I think there is an opportunity to provide useful information to app developers when the router fails to send a request to their application.

I have some specific idea about what I'd like to see logged and we can debate those.  But the main point of the issue is that I think my app developers should have some way of knowing about some of the issues the router may occasionally run into when attempting to forward a request to their application.

Do you agree or disagree with that basic premise?

**Comment by shalako** [comment]
I do not disagree with the basic premise. What I tried to convey in my last comment is our team has suggested that this is already happening for some errors. 

Gorouter sends access log messages to local file, an external syslog consumer, and to the local metron agent. Only messages with an app id are sent to the metron agent, which forwards those messages to Loggregator, and is how a developer sees router log messages when subscribed with `cf logs myapp`. The router log messages a developer sees in this way are actually access log messages. 

Our team has suggested that if the router receives a request and finds a match in the routing table, but fails to connect to an app, the same error logged to access log is exposed to the developer in the same way.

**Comment by youngm** [comment]
@shalako Thanks for the clarification.  I do see I had no idea that anything was being sent.  I see a 502 access log message when an application crashes mid request.  That is good but not super helpful since it is not obvious that the app didn't handle the request.  But still useful.

We also might have some wildcard routes that may be getting in the way of log messages we aren't seeing in my tests.

Let me take a closer look my use cases and I'll see if I can better refine what it is I'd want based on what the router is already doing.  I'll reopen the issue when I have more information.

Thanks Shannon!

**Comment by youngm** [comment]
@shalako I've spent some time digging deeper.  The Router does log a 502 in situations where I didn't think it did.  So, now that I'm on the same page as you with current functionality, this issue boils down to a request for the router to log individual connection errors.

I'm thinking a message like the following should be logged for each failed attempt to connect to an instance in addition to the 502 already logged.

```
[RTR/0]      ERR some.host.com app_index: 1 vcap_request_id:715f56c0-2645-4daa-6015-2af787e56c9d error: dial tcp i/o timeout
```

These messages would go to the ERR log not OUT.  The vcap_request_id can be used to follow the attempts and eventual success or failure of the request.

I don't think that messages like this would equate to "noise" since I cannot think of a reason why a properly running CF deployment would ever have cause to log an error like this that the user couldn't act on.

Thoughts?

**Comment by shalako** [comment]
The request is clear. Thanks, Mike. 

I can't prioritize a solution now, but we can keep the issue open to gather +1s from others and we've got the linked story to track it.

**Comment by youngm** [comment]
Thanks @shalako, would you accept a PR for this?  Or do you think you need more +1s gathered before you'd accept a PR?

**Comment by shalako** [comment]
I'm open to a PR. Need an ok from the team; what do you think @shashwathi ?

To be clear, the only change is for gorouter to log a message to access log when it fails to connect to a backend found in the routing table and it will retry another backend. These errors are not returned to the client, as it will try another backend transparently. If it is has tried the last backend for the route, it already logs the error returned to the client.

**Comment by shashwathi** [comment]
@shalako @youngm : From an app developer perspective logging retrying to another backend could be useful information. +1 for the PR.

Regards
Shash

**Comment by youngm** [comment]
I wish I had time for this but I don't and with the move to istio this would be fruitless.  I'll close for now.  Sorry for consuming your time considering it only to not contribute anything.  Thanks!
