### ISSUE TITLE
Improve documentation around the properties :`load_balancer_healthy_threshold` and `drain_wait` 

### ISSUE THREAD

**Issue by anoop2811** [cloudfoundry/gorouter#160]
Currently the documentation provided in https://github.com/cloudfoundry-incubator/routing-release#configure-load-balancer-healthchecks-for-gorouter with regard to how to calculate the values for the mentioned properties are not clear. We have had a slack conversation here(https://cloudfoundry.slack.com/archives/routing/p1480623540001158) about this and if that is the right way to calculate the appropriate values, they should be documented. Additionally, as per the conversation, the calculation,  `load_balancer_healthy_threshold == (healthy threshold + 1) * (healthcheck interval)`. Looking at the code, the server does not start till this time is reached, is there any reason for extending the threshold instead of using `load_balancer_healthy_threshold == healthy threshold  * (healthcheck interval)` ?

**Comment by Nino-K** [comment]
Thanks @anoop2811 for bringing this up to our attention. We marked this bug to investigate further and as an outcome we will be updating the docs accordingly.

@aaronshurley & Nino

**Comment by aaronshurley** [comment]
@shalako @abbyachau This story requires a small investigation and update of our documentation. Can we prioritize this?

Regards
Aaron & @shashwathi

**Comment by shalako** [comment]
Prioritized

**Comment by shalako** [comment]
We've updated our startup behavior to simplify the process, and we've updated the docs also. 

Closing for now; please let us know if you still have questions or concerns.
