### ISSUE TITLE
X-Forwarded Headers being modified

### ISSUE THREAD

**Issue by warroyo** [cloudfoundry/gorouter#164]
I am seeing an issue when using a load balancer that terminates TLS in front of the gorouters. We are injecting  `X-Forwarded-Proto` and `X-Forwarded-Host` headers before passing the traffic through to the gorouters. However when the application attempts to use these headers they seem to have been modified again. 

The headers coming out of our load balancers before being passed to the routers look like this (I have modified the actual hosts for privacy) :

````
X-Forwarded-Host: my.external-url.com
X-Forwarded-Proto: https
````

After passing through the router, the app sees this:

````
X-Forwarded-Host: my.external-url.com, myapp.cfdomain.com
X-Forwarded-Proto: https, https
````

is this expected behavior? Is there a way to prevent this form happening ?

**Comment by shashwathi** [comment]
@warroyo : 

`X-Forwarded-Proto` header should not overridden if it is already set in the request. We have an environment where ELB is terminating SSL and adding `X-Forwarded-Proto` header but `gorouter` respects this value and forwards the same to request. 
`gorouter` does not set `X-Forwarded-Host` header. If client or LB is setting this header `gorouter` should pass them through.

To debug this issue further follow instruction on this [repository](https://github.com/cf-routing/golang-app) to stage the app. Connect to the application without LB so you eliminate external components as the problem. You might have to be in the network to do the following steps.

```
curl -vv -H"X-Forwarded-Host:test" -H"Host:golang.cfdomain.com" GOROUTER_IP:PORT/headers
```
```
curl -vv -H"X-Forwarded-Proto:https" -H"Host:golang.cfdomain.com" GOROUTER_IP:PORT/headers
```

Verify the app is receiving your header and let us know if it is still modified?

Regards
Shash

**Comment by warroyo** [comment]
@shashwathi thank you for the information. I have tested with the go app provided  and i do not see the duplicate headers. This issue does not seem to be related to the go router or load balancer. I think this issue can be closed now.
