### ISSUE TITLE
Pass client cert information through to backend

### ISSUE THREAD

**Issue by sorenh** [cloudfoundry/gorouter#167]
If a requestor provides a client certificate and the gorouter terminates SSL for me, I at least need access to the client cert's DN. I could make do with the full certificate, but just the client DN would make things quite a bit easier.

**Comment by shashwathi** [comment]
@sorenh : Thank you for reporting this issue. After looking at [Apache docs](https://httpd.apache.org/docs/current/mod/mod_ssl.html), there are some standard headers used to pass SSL information through to backend.
  
We could consider using the header `SSL_CLIENT_S_DN` / `SSL_CLIENT_I_DN ` for your case which corresponds to subject DN / issuer's DN in client's certificate. Upon reading further about subject DN and issuer DN, it feels like you need issuer DN but correct me if I am wrong.

@shalako @abbyachau 
We can also take this opportunity to pass in minimal SSL headers to backend request like full client cert, algorithm used to verify the cert. 

Regards
Shash

**Comment by sorenh** [comment]
@shashwathi Yeah, you're spot on. Those env vars would totally do the trick. The issuer DN would normally be required, because client certificates usually aren't signed by a CA in the root cert list.

**Comment by shalako** [comment]
Hello @sorenh 
Please confirm how you would want the issue DN exposed.

Would you want the Gorouter to forward the DN in an http header to the app? Example:
```
HTTP_SSL_CLIENT_I_DN: "C=MY,ST=some state,L=some city,O=Expensive Certs inc,OU=X.509 certs,CN=very expensive certs"
```

Should we avoid writing this header in logs or emitting it in metrics?

Is the issuer DN sufficient, or do you also need the subject DN?

This seems like a very lightweight version of mTLS. Is it acceptable that the app does not terminate the client TLS request directly? Are you using other means to encrypt the request from Gorouter to app, or is leg unencrypted?

**Comment by sorenh** [comment]
Issuer DN and subject DN are both required. Including them in the logs sounds convenient, but I'm not sure if it's considered too sensitive for that.

I don't think I understand your question re: the app not terminating the client TLS request directly. If the gorouter terminates the request, the app can't also terminate it.

As for securing the communication between the Gorouter and the app, I don't know how it's set up in our organization, to be honest. I don't even know what options PCF provides for this.

**Comment by avasseur-pivotal** [comment]
(I am watching this discussion) You can terminate TLS at the app by using the Cloud Foundry TCPRouter so that the (HTTPS) Router is not terminating it.

**Comment by sorenh** [comment]
Right, but I can't BOTH have the gorouter terminate it and the app terminate it. :)

**Comment by sorenh** [comment]
I'm getting a request from "my people" to add an option to include the whole cert.

**Comment by shalako** [comment]
So only the cert, as the issuer and subject can be determined from the cert?

**Comment by sorenh** [comment]
No, sorry, I should have been more clear.

I imagine most people will be happy with just issuer and subject DN. Let's keep them happy :)

We, however, also would like the cert as it was provided by the client.

**Comment by shalako** [comment]
If you don't need issuer and subject DN, we won't add it. No one else is asking, and we only want to make change we know people will use now. So it sounds like you only need the cert.

**Comment by sorenh** [comment]
This is becoming critical. What can I do to push this forward?

**Comment by shalako** [comment]
It is still not clear to me whether you need the cert, or some specific fields from the cert, or both. 

I would like to avoid picking some fields from the cert if it is possible you or another could come back in six months and that the router send more fields. So exploring ways to send the whole cert is interesting.

What flexibility do your app developers have in ways to receive the requested data? Headers? Cookies? Are they using libraries that expect specific header/cookie names?

> I don't think I understand your question re: the app not terminating the client TLS request directly. If the gorouter terminates the request, the app can't also terminate it.

My understanding of mTLS is that the server (the CF app in this case) receives the client cert from the client directly. If several components are terminating and re-encrypting upstream, including Gorouter, then they must all pass along the client cert. Is that acceptable, or do we have to figure out how the app is the first node to terminate?

**Comment by sorenh** [comment]
Apache passes SSL_CLIENT_S_DN / SSL_CLIENT_I_DN to applications. I think modeling after Apache is generally a sound approach. That's about as battle tested as it can be.

However, my engineers expressed an interest in getting the raw cert passed through. So I guess I stand by my earlier statement: 

The SSL_CLIENT_S_DN / SSL_CLIENT_I_DN headers are pretty handy and would be fine for most people. Just discarding/ignoring the client cert seems uncool. We, however, would like the raw cert. Strictly speaking, we only *need* the cert.  Personally, for my not-at-work purposes, I would by far prefer the SSL_CLIENT_S_DN / SSL_CLIENT_I_DN headers, but if it really can only be one or the other, it's gotta be the cert.

Currently, the engineers terminate TLS in their apps directly. They're aware that they'll need to get the cert from someplace else (an HTTP header, presumably).

Passing along the validated client cert from the initial TLS termination point (i.e. the gorouter) is fine. It gives the backend application all the information about the client's identity it could possibly require (just as a header rather than from its TLS handshake), we have a chain of custody for this identity that meets our security standard, and we have the full flexibility of the gorouter's routing capabilities and route services. Everybody wins.

**Comment by shalako** [comment]
@dsyer 

In this thread we're discussing having Gorouter terminate TLS and forward the client cert to an app so it can do some validation/authentication. The open question is in what format the cert is forwarded (header, cookie, etc).  

I presume spring security provides a framework interface for app developers to consume data from a client cert for validation? Is there a conventional format that Spring consumes the client cert forwarded by an upstream component handling TLS termination (gorouter)?

We'll be exploring implementations by other proxy vendors.
Thank you

**Comment by shalako** [comment]
@sorenh 
Assuming Gorouter won't be the first component in the data path to terminate TLS, and a load balancer is establishing a TLS connection with Gorouter, and the load balancer is not using the originating client cert to do so, in what format should Gorouter expect to receive the client cert?

**Comment by shalako** [comment]
This is currently in implementation: https://www.pivotaltracker.com/story/show/147569221

**Comment by shashwathi** [comment]
@sorenh : This feature is present in [latest routing release](https://github.com/cloudfoundry-incubator/routing-release/releases/tag/0.160.0). Feel free to open to another issue if you notice any issue.

Regards
Shash
