### ISSUE TITLE
gorouter logs AccessLogRecord-not-set-on-context error every time health endpoint hit

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/gorouter#168]
## Issue

I'm running CF 253.  I don't have logging to any access log file turned on.  I see the following error in my logs when I hit the /health endpoint:

```
{"log_level":3,"timestamp":1489086054.869523,"message":"AccessLogRecord-not-set-on-context","source":"vcap.gorouter.router","data":{"error":"failed-to-access-log-record"}}
```

## Steps to Reproduce

Hit health endpoint and see error log message

## Expected result

Not see error log message for a normal component interaction.

## Current result

See error log message

## Possible Fix

Not log error for health hit without an AccessLogRecord

**Comment by shashwathi** [comment]
@youngm : Thank you for reporting this, we are aware of this bug and currently working on it. 
For details follow story https://www.pivotaltracker.com/story/show/141367603

Regards
Shash

**Comment by youngm** [comment]
Oh, sorry I forgot to check tracker.  Glad you're aware of it.  Thanks!

**Comment by aaronshurley** [comment]
Closing this issue as it has been accepted on Pivotal Tracker.
