### ISSUE TITLE
Route services cannot determine if original request via TLS

### ISSUE THREAD

**Issue by cholick** [cloudfoundry/gorouter#170]
## Issue
As a route service author, I want to be able to determine if the original request to the app was via `http` or `https`.

## Context

The url scheme on the `x-cf-forwarded-url` header isn't useful, as this is driven via config in `routeservice.go`

```go
if r.config.RouteServiceRecommendHttps() {
	recommendedScheme = "https"
} else {
	recommendedScheme = "http"
}
```

That leaves `x-forwarded-proto`. This header is accurate in the context of a deployment like bosh-lite, where an elb isn't fronting traffic. In the clouds I've tested on (GCP and AWS), the load balancer *doesn't* perserve an incoming `x-forwarded-proto`. Since the router always makes the request to a route service over `https`, and that request passes through the cloud providers load balancer, the `x-forwarded-proto` will always be `https`, regardless of how the original request to the app was made.

## Steps to Reproduce

1. Bind a route service to an app in AWS or GCP
2. Make a request to the app over `http`
3. View the headers received by the route service: it has no way to determine if the original app request was over `http` or `https`.

## Expected result

I would expect some header to change based on if the original request was over `http` or `https`.

## Current result

All headers are either configuration driven (`x-cf-forwarded-url` with `RouteServiceRecommendHttps`) or explicitly show https (`x-forwarded-proto`).

## Possible Fix

Given `x-forwarded-proto` is changed by the cloud provider, an additional custom header seems like a decent workaround.

**Comment by shalako** [comment]
We rely on the load balancer to provide the scheme of the originating request in `x-forwarded-proto`. The platform itself depends on it (UAA will reject requests that do not contain `x-forwarded-for: https`), and many apps depend on it also.

A custom header would require configuration of a load balancer to something special for this header, just as we require load balancers to be configured to forward `x-forwarded-proto`. Only the load balancer knows this information. Gorouter has no other means of knowing.

Gorouter should forward the same values of `x-forwarded-proto` to a route service as were in the request it receives from the load balancer. If it does not let us know and we can fix that.

**Comment by cholick** [comment]
I'm only talking about route services: the request is intercepted and there's the additional round trip through the external ELB. In this situation, the `http` request will have `x-forwarded-for` of `https`.

Relying on the load balancer to preserve `x-forwarded-proto` doesn't work for the major cloud providers I tested (AWS and GCP), though it does work for HAProxy. In requests made to an app via `http` with a route service, the `x-forwarded-proto` is flipped to `https` (reflecting the `https` request made the to route service).

**Comment by shalako** [comment]
In older versions of cf-release, if your route service ran as an app on CF, then the request from Gorouter to the route service would go back through the LB and the value of x-forwarded-proto could be modified. Is that what you mean?

In cf-release v259 (routing release 0.152.0), we modified Gorouter to detect if the route service was an app, and forward the request directly to it. In this case, the header should not be modified. The request from the route service to the app would go through the LB, however, and the app would receive the header set to the scheme of the request sent by the route service.

What version are you running?

**Comment by cholick** [comment]
I cloned and built master at the time of filing this bug to swap a binary into cf with additional debugging information, but that does pre-date `0.152` by a week or so. I can re-test with current master. May take me a bit to set all this up again, please don't close in the meantime.

**Comment by cholick** [comment]
I still see this behavior in `0.154.0`

**Comment by shalako** [comment]
Prioritizing for engineering review.

**Comment by shubhaat** [comment]
@cholick - we already have a story on our backlog (https://www.pivotaltracker.com/n/projects/1358110) to address #201 . We think this will also resolve the issue you bring up on getting the scheme for a request through the X-Forwarded-Proto header.

**Comment by zachgersh** [comment]
talked to @cholick offline. Closing for now.
