### ISSUE TITLE
Customizable error pages (instead of 404 route dous not exist)

### ISSUE THREAD

**Issue by jtwaleson** [cloudfoundry/gorouter#171]
## Issue

There is no user friendly page when an app is stopped.

## Context

We're building a platform based on Cloud Foundry, and would like to show our users something else than the default "Requested route (xyz) does not exist.".

Note: we have complete control over the clusters, users do not work with cf cli themselves.

## Expected result

Per case:
* app does not exist -> generic error page
* app exists but is not running -> user definable error page

## Current result

"Requested route (xyz) does not exist."

## Possible Fix

I think this is completely beyond the scope of the gorouter, but I think these two pragmatic solutions would allow us to build this functionality with a custom app.

### 1 - wildcard routes also match the main domain

This could be solved with a custom app that returns error pages with a wildcard route. This works, because if the app is stopped, the app with the wildcard route will get the traffic, that can serve the standard or custom error pages. Unfortunately, this fails for custom domains such as `mydomain.com` without a hostname. In that case, the wildcard `*.mydomain.com` does not match if the app is stopped.

In this case, we simply add a wildcard route for each custom domain to the "custom-error-pages" app.

### 2 - a global fallback route
The possibility to register a cluster-wide fallback route, that app will get all the non-matching traffic, and can decide if it returns 404, 503, etc.

**Comment by aaronshurley** [comment]
@jtwaleson We do not currently support customizable 404 pages. I think this feature may surpass the responsibilities of the gorouter but know that others have asked about this before. @shalako do we have a recommended approach for this?

-Aaron && @belinda-liu

**Comment by shalako** [comment]
@jtwaleson and I spoke about this request at CF Summit. While the feature seems quite reasonable, I don't have enough evidence of market value to prioritize it, when compared to features that are in greater demand.

It doesn't appear that we could apply the requested behavior consistently across the tree of domains, as this would not be backwards compatible. Although the use case appears valid, I'm concerned with a exception to behavior for root domains as this sacrifices predictability.

Currently a request for `foo.bar.com` will match wildcard route `*.bar.com` if there is no route `foo.bar.com`, or the app for it is down. 

The requested feature would route requests for `foo.bar.com` to the route `*.foo.bar.com` if there is no route `foo.bar.com` or the app is down. But what if there is also a wildcard route for `*.bar.com`? Requests for `foo.bar.com` are currently routed to `*.bar.com` and with the proposed change we would send them to `*.foo.bar.com`. That would be a backward incompatible change.

@jtwaleson Let me know if you have ideas for how to introduce the feature with a consistent UX.

**Comment by MarcPaquette** [comment]
I have a customer who is interested in this functionality.

**Comment by shubhaat** [comment]
As part of our focus on replacing existing CF routing subsystems with Istio and Envoy, we will return a different status code for the two use cases you mentioned:
- route is not mapped to an app, or does not exist -> 404
- route mapped to an app but app is stopped or crashing -> 50x

Will this be a help to you, or do you also need the ability to configure the edge router to send requests that meet these criteria to apps running on the platform that serve a custom, branded, html error page?

**Comment by jtwaleson** [comment]
@shubhaat good to see there are going to be some changes here!

Although adding 50x is a good step, I don't yet see how differentiation between 404 and 50x solves the issue of branded error pages, so I think the request still stands.

Are custom error pages expected to be implemented in the edge router (so not the CF go-routers)? In that case, the edge router needs to be able to distinguish between normal apps returning 404s / 503s and the go-router returning 404s / 503s because the apps are offline / not there. It can do that via two mechanisms:

1. response headers, such as: "X-CF-Go-Router: APP_OFFLINE" and "X-CF-Go-Router: NO_SUCH_ROUTE"
2. configurable, non-standard HTTP response codes (an operator might configure 598 for stopped apps, 599 for unmapped routes)

Depending on the edge router technology, it may be much easier to serve a custom response with option 2 than on option 1. For example, in nginx (which we use), you can use `$upstream_status` to redirect traffic.

On the whole I would strongly prefer an option within CF rather than pushing this logic to the edge routers.

**Comment by zachgersh** [comment]
@jtwaleson - would you mind writing this up as a feature here: https://github.com/cloudfoundry/istio-release (that way @shalako can keep track of it as we work on istio features)?

**Comment by utako** [comment]
Hi @jtwaleson,

I'm going to close this in favor of the issue I hope you open in our [Istio Release](https://github.com/cloudfoundry/istio-release) to capture this. Please let us know if you have any other questions.

Thanks,
@utako, CF Routing Team
