### ISSUE TITLE
Abnormal <Start Date> format in access logs

### ISSUE THREAD

**Issue by David-Pivotal** [cloudfoundry/gorouter#175]
## Issue

The `<Start Date>` in access logs should have a format of `[09/05/2017:14:46:19.978 [+0000]` as per [Common Log Format](https://httpd.apache.org/docs/1.3/logs.html#combined). However I find an abnormal format, `[2017-05-09T14:41:36.452+0000]` in access log. 
Is it by design or shall we have a plan to make this field consistent?

**Abnormal format**
{"cf_app_id":"56c8afae-ee88-4129-a6ed-6f06b2d5c302","cf_origin":"firehose","deployment":"uswest2-sb-cloudfoundry","event_type":"LogMessage","ip":"10.72.66.10","job":"router_z1","job_index":"a09eb913-b398-4fbc-a232-bc27c0026b7e","message_type":"OUT","msg":"egress.xxxxxxxx.io - **`[2017-05-09T14:41:36.452+0000]`** \"GET /egress-status/tcp/smtp.xxxxxxxx.com/587 HTTP/1.1\" 200 0 27 \"-\" \"Ruby\" \"10.72.67.173:18102\" \"10.72.68.136:61009\" x_forwarded_for:\"-\" x_forwarded_proto:\"http\" vcap_request_id:\"bca0fa8b-a3a8-4cb7-617e-311d46b29453\" response_time:6.036001242 app_id:\"56c8afae-ee88-4129-a6ed-6f06b2d5c302\" app_index:\"-\" x_b3_traceid:\"e5df009c249008ba\" x_b3_spanid:\"e5df009c249008ba\" x_b3_parentspanid:\"-\"\n","origin":"gorouter","source_instance":"0","source_type":"RTR","timestamp":1494340902488413316}

**Normal format**
{"cf_app_id":"a5271137-d516-4846-87f6-d693876ee610","cf_origin":"firehose","deployment":"uswest2-pr-cloudfoundry","event_type":"LogMessage","ip":"10.72.11.10","job":"router_z2","job_index":"20c1d1f3-8f5b-4552-8186-79fe688af6f2","message_type":"OUT","msg":"c5435fa9-b655-4a30-b6a6-384295744818.xxxxxxxx.io - **`[09/05/2017:14:46:19.978 +0000]`** \"GET /oauth/token?grant_type=client_credentials HTTP/1.1\" 200 0 2574 \"-\" \"Apache-HttpClient/4.5.2 (Java/1.8.0_121)\" 10.72.11.55:37481 x_forwarded_for:\"52.xxx.xxx.xxx\" x_forwarded_proto:\"https\" vcap_request_id:e0b03688-d7a1-4a0e-62e4-52e49ee0048f response_time:0.019445449 app_id:a5271137-d516-4846-87f6-d693876ee610 app_index:- x_b3_spanid:\"3068ebc39dac12b3\" x_b3_traceid:\"c6ae9610cb472f04\"\n","origin":"gorouter","source_instance":"0","source_type":"RTR","timestamp":1494341179997632016}

**Comment by shalako** [comment]
We use ISO 8601 for representing dates, as it is an international standard. In some countries the day is written first, so `09/05/2017` is ambiguous. It could mean either May 9 or September 5, depending on who you ask. YYYY-MM-DD is the unambiguous international standard.

https://xkcd.com/1179/
