### ISSUE TITLE
Need TLS version to be configurable

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/gorouter#177]
## Issue

TLS is hard coded to 1.2 only at https://github.com/cloudfoundry/gorouter/blob/master/router/router.go#L263.

## Context

We just ran into a similar issue with HAProxy (https://github.com/cloudfoundry/cf-release/issues/1204) and since we are planning to switch to gorouter for TLS termination we'll run into the same issue here.

## Expected result

Minimum TLS version should be user configurable.

## Possible Fix

Please default to 1.2 but make the version configurable in the manifest.

**Comment by shashwathi** [comment]
@amhuber : 

Thank you for reporting this issue. Out of security concerns, we dropped support for all TLS versions below 1.2 but I see your concern for making this configurable if your platform decides to support different TLS versions. 

@shalako thoughts or concerns about this request? 

Regards
Shash

**Comment by amhuber** [comment]
I definitely understand the security concern and if I could I'd prefer to cut off the older TLS profiles but clearly not everyone in a large organization is ready all at once to move forward.  :-)  This would effectively change nothing in the default deployments, just give operators the option to change it as needed.

Aaron

**Comment by shashwathi** [comment]
@amhuber : I agree that default setup should reject anything below TLS1.2 versions.

Feel free to prioritize this @shalako

Regards
Shash

**Comment by shalako** [comment]
@amhuber Would you prefer to use a manifest property that took a minimum version or a list of enabled versions?

What versions do you want to enable?

Thank you

**Comment by amhuber** [comment]
For now we'd want to re-enable the versions that were removed (1.0 and 1.1).  I'd be fine with either specifying a minimum version or providing a list of versions to support.  Whatever is the simplest to implement is fine.

**Comment by cppforlife** [comment]
here is how bosh does it:

https://github.com/cloudfoundry/bosh/blob/master/jobs/director/spec#L66

default to recommended, but allows customization.

**Comment by shalako** [comment]
Dmitriy, is that a space delimited list or comma delimited list? What is the syntax of the valid values? The spec description doesn't say.

**Comment by cppforlife** [comment]
space delimited for nginx.

**Comment by shalako** [comment]
Prioritized for implementation

**Comment by shalako** [comment]
We've added support for `router.min_tls_version`; it will be available in the next release of routing-release (or the following release of cf-release).

Thank you
