### ISSUE TITLE
Routing table null record

### ISSUE THREAD

**Issue by fghorbel** [cloudfoundry/gorouter#178]
Thanks for submitting an issue to `gorouter`. We are always trying to improve! To help us, please fill out the following template.

## Issue

- Failure of Gorouter routing table 

while true; do curl -s http://admin:1qtyuydjdfg6574r\$@localhost:8080/routes>/tmp/gorouer.jq && sleep 1s && echo "#######################$(date)########################" | tee -a /tmp/gorouter.poll&& /var/vcap/packages/jq/bin/jq -r ".\"machine.apps.toto.com\"[0].address" /tmp/gorouer.jq | tee -a /tmp/gorouter.poll ; sleep 1s; done

```
10.13.17.8:60042
#######################Fri May 26 20:31:57 UTC 2017########################
10.13.17.8:60042
#######################Fri May 26 20:31:59 UTC 2017########################
null
#######################Fri May 26 20:32:01 UTC 2017########################
null
#######################Fri May 26 20:32:03 UTC 2017########################
null
#######################Fri May 26 20:32:05 UTC 2017########################
null
#######################Fri May 26 20:32:07 UTC 2017########################
null
#######################Fri May 26 20:32:09 UTC 2017########################
null
#######################Fri May 26 20:32:11 UTC 2017########################
10.13.81.6:60034
#######################Fri May 26 20:32:13 UTC 2017########################
10.13.81.6:60034
#######################Fri May 26 20:32:16 UTC 2017########################

```

The time of null output  matches exactly with  the Haproxy 404 HTTP error

```
May 26 20:32:05 localhost haproxy[25774]: 9ba9f570-2216-4024-ab45-8c4661996aba 10.10.1.172 - [26/May/2017:20:32:05.852] "POST /status HTTP/1.1" 404 [reqId:"9a2a0cd81b556a38771c63fd7dac614f84978bc53c9a017923d879975d0d3bf0"] "" 12 "node1-10.13.81.5"

....

May 26 20:32:16 localhost haproxy[25774]: 9ba9f570-2216-4024-ab45-8c4661996aba 10.10.1.172 - [26/May/2017:20:32:16.504] "POST /status HTTP/1.1" 404 [reqId:"cf2b52b773a8ba5f6a414ec05abc919b10227d7f011e8f5f1c0e2872487d6310"] "" 18 "node0-10.13.17.7"

```

## Context

CF stress test. We run a stress test against CF diego. We have noticed some requests return 404 or 502 HTTP error code. 

## Steps to Reproduce

Perform a high traffic against CF, and you will see the errors...

## Expected result

All requests should return 200 HTTP code
## Current result

For small period of time we got a bunch of 404 HTTP error code

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` Output Results
2017-05-24T20:06:15.617 502 Bad Gateway
2017-05-24T20:06:15.621 502 Bad Gateway
2017-05-24T20:06:15.625 502 Bad Gateway
2017-05-24T20:06:15.633 502 Bad Gateway
2017-05-24T20:06:15.636 502 Bad Gateway
2017-05-24T20:06:15.639 404 Not Found
...
2017-05-24T20:07:07.803 404 Not Found
2017-05-24T21:36:57.416 401 Unauthorized
2017-05-24T21:48:22.425 502 Bad Gateway
2017-05-24T21:48:22.474 404 Not Found
...
2017-05-24T21:49:08.451 404 Not Found
2017-05-24T22:12:27.197 502 Bad Gateway
2017-05-24T22:12:27.219 502 Bad Gateway
2017-05-24T22:12:27.239 404 Not Found

[if relevant, include a screenshot]

**Comment by shashwathi** [comment]
@fghorbel : 

Thank you for filing this issue. We run performance tests against gorouter in our CI but as a standalone job instead of gorouter in CF context. 
Can you give us the more details about the test setup
- number of requests
- concurrency
- Number of cells
- Number of routers
- Is the client doing the stress test within the network(targetting gorouter directly) or through the Load balancer or haproxy? 
- What is the backend application used for the test?
  
Regards
Shash

**Comment by fghorbel** [comment]
@Shash

Thank you for you answer, it turned out it s out of memory issue. We didn t give the application enough memory for that reason, the container got stopped and restarted. 

Thank you

**Comment by shashwathi** [comment]
@fghorbel 

Thats great. If an application container is out of memory, gorouter will fail to establish any TCP connections which explains the 502s.

I am going to go ahead an close this issue for now. Feel free to open another issue if you have any problems.

Regards
Shash
