### ISSUE TITLE
Metrics should indicate host header values / apps / app instances

### ISSUE THREAD

**Issue by jim80net** [cloudfoundry/gorouter#180]
## Issue

Metrics should direct operator towards problem resolution. Give me a hint, won't you?

## Context

When I manually observe a deviation from standard operating values:
![](https://image.ibb.co/jGU38Q/image.png)

Then I want to figure out where to look next. 

## Steps to Reproduce

1. observe gorouter.rejected_requests metric that is higher than average
1. attempt to figure out why

## Expected result

1. I am directed towards the cause by observing that either
- a particular app is responsible
- all apps report rejects, indicating a systemic issue

## Current result

1. I know something is wrong, somewhere, and must attempt to figure this data out from other sources. 
1. log into logsearch
1. attempt to figure out how to parse for 5xx errors in logs
1. wait as ELK parses my query
1. wait some more. 
1. get something that doesn't really match what i want. 
1. reference [regexp queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html)
1. try something
1. syntax error
1. give up
1. send an email asking if someone is noticing any issues with their app. 
1. feel bad
1. finally figure out the query to use against logsearch
1. much fanfare and congratulations
1. normal operations until...
1. ...it happens again
1. where did i put that script? 
1. search desperately in dropbox
1. I can't find it
1. sigh
1. log into logsearch...
1. attempt to figure out how to parse for 5xx errors in logs
 
## Possible Fix

Having the host of the rejected requests delivered as metadata to the rejected requests ( and other metrics like latency and bad gateway) allows me to determine that the issue is systemic or a particular app, and take appropriate action.

**Comment by aaronshurley** [comment]
@jim80net We understand what you're asking for and it should be technically feasible with updates to our dropsonde metrics emitter. You specifically mentioned `rejected_requests`, `bad_gateways`, and `latency` but do you think there would be value in modifying any of the others https://docs.cloudfoundry.org/running/all_metrics.html#routing? Those three metrics are more useful for troubleshooting but not sure if you're encountering other particular pain points.

@shalako do you have any thoughts to emitting additional metadata/tags for our metrics?

**Comment by jim80net** [comment]
Going over the doc, I believe the metrics

`bad_gateways`, 
`latency`, 
`rejected_requests`, 
`requests`, 
`responses`, 
and `responses.*`

would be the most useful.

**Comment by jim80net** [comment]
Bump

**Comment by shubhaat** [comment]
We are currently working on replacing the current routing subsystem with Istio/Envoy, read more [here](https://docs.google.com/document/d/1LgLY0g39fzpg1_4zTckbH1mOuuSKGvYwp2tkakoe9ys/edit#heading=h.tj1oxhcb47cj). The metrics emitted by Envoy for each application (Envoy calls these clusters) are documented [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/cluster_manager/cluster_stats). We believe that this should provide the data you are looking for.

**Comment by zachgersh** [comment]
closing as a won't fix as we _hope_ this will be address in the new world.
