### ISSUE TITLE
Allow operators to enable TCP keepalives between gorouter and apps

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/gorouter#185]
Thanks for submitting an issue to `gorouter`. We are always trying to improve! To help us, please fill out the following template.

## Issue

When an application instance disappears without closing the connections (e.g. hard VM crash) gorouter keeps all connections to that instance open until they time out. 

## Context

With high-enough crash rates this can lead to a lot of broken connections on the gorouter side, each using CPU/memory resources (the CPU bit is a little surprising, but by profiling gorouter we noticed it's basically due to the timers created by maxLatencyWriter).

A solution is to lower the timeout, but this has additional side effects (e.g. it also affects how much time gorouter waits during drain for active connections to go idle before killing them) and in any case there are good reasons to allow apps longer timeouts.

A better solution is to allow operators to enable TCP keepalives to the instances. This would allow e.g. to aggressively prune broken connections in seconds while still allowing longer idle timeouts.

Currently gorouter offers no option to enable/configure TCP keepalives to the instances.

## Steps to Reproduce

- open many active connections to an application instance
- hard kill the VM (or simulate blackhole-style network disconnection via iptables) so that the connections on the gorouter side are not closed
- notice that connections on gorouter side will remain alive, consuming resources, until timeout expires

## Expected result

- if TCP keepalives are enabled and configured to e.g. 3 missing ACKs, one every 5 seconds, upstream connections should be closed in 15 seconds max, regardless of IdleTimeout

## Current result

- connections remain until IdleTimeout expires

## Possible Fix

if enabled via config (manifest), call SetKeepAlive and SetKeepAlivePeriod on the TCP socket to the instance

**Comment by CAFxX** [comment]
CPU profile of a gorouter showing high CPU utilization due to many open connections (as described above)
[profile001.pdf](https://github.com/cloudfoundry/gorouter/files/1172543/profile001.pdf)

**Comment by shalako** [comment]
Hello @CAFxX 
You can enable keepalive connections to backends using `router.max_idle_connections`. Have you tried this?

**Comment by CAFxX** [comment]
these are HTTP keepalives (to reuse idle, non-broken TCP connections), this ticket is about TCP keepalives (to detect broken TCP connections)

**Comment by shashwathi** [comment]
@CAFxX : There is a [bosh plugin](https://github.com/cloudfoundry/os-conf-release) to enable this feature.

Regards
Shash

**Comment by CAFxX** [comment]
@shashwathi we are well aware of that bosh release but it doesn’t do what we ask here. 

The bosh release allows you to set the system wide defaults but it doesn't allow to enable keepalives. In fact Linux doesn't allow to enable them systemwide (because the relevant RFCs say that they should be disabled by default). 

The only way is for applications that need them to enable them on individual sockets. Once keepalives is enabled on a socket the system wide defaults that the bosh release sets will be in effect for that socket unless manually overridden by the application. 

What we're asking in this issue is for gorouter to enable keepalives on connections to the backends.

**Comment by shashwathi** [comment]
@CAFxX  : 

Thank you for explaining that. I guess as part of this story we can investigate what should be the recommended value for TCP keepalive timeout. 

@shalako : Looks good from engg side. Feel free to prioritize this. 

Regards
Shash

**Comment by CAFxX** [comment]
> we can investigate what should be the recommended value for TCP keepalive timeout

@shashwathi if I may my recommendation is to make this configurable and, at least for now, opt-in (i.e. off by default, as it is now)

**Comment by shashwathi** [comment]
@CAFxX 

We still need to provide documentation for operators to set this value. What are the implications of setting it too high or low.

**Comment by CAFxX** [comment]
> We still need to provide documentation for operators to set this value. What are the implications of setting it too high or low.

Sure, agreed. Especially what are the interactions with the other read/write timeouts and HTTP keepalives (persistent connections)

**Comment by shalako** [comment]
To help us understand the desired operator experience, provide an example job spec entry for the new property or properties.

Can we have one property that controls whether the feature is enabled and what the timeout is, by either hardcoding the number of failed checks or the frequency? 

e.g. 
```
router.backends.tcp_keepalive_unhealthy_threshold:
  description: Number of failed TCP healthchecks before closing the connection. Frequency is 5s. A value of 0 disables TCP keepalives.
  default: 0
```

**Comment by CAFxX** [comment]
I would suggest to surface both interval and count (allowing to set the interval allows to use this also for keeping connections alive on middle boxes). Delay can be safely set to the same value as interval. 

More importantly, I'd suggest to clearly describe what is the actual "target effect" of the keepalives.

```
router.backends.tcp_keepalive_count:
  description: |
    Number of failed TCP keepalives to send before closing the connection. 
    Broken connections will be closed if the backend does not respond
    to `router.backends.tcp_keepalive_count` TCP keepalives in a row (i.e.
    if the backend does not send any valid TCP packet for 
    ((router.backends.tcp_keepalive_count + 1) * router.backends.tcp_keepalive_interval) seconds.
    This value maps to TCP_KEEPCNT.
    A value of 0 (the default) disables TCP keepalives to the backends.
  default: 0
router.backends.tcp_keepalive_interval:
  description: |
    Initial delay and interval of the keepalives in seconds.
    This property maps to TCP_KEEPIDLE and TCP_KEEPINTVL. It is ignored if 
    `router.backends.tcp_keepalive_count` is 0.
  default: 5   # I'm using 5 here just because it was in @shalako's example
```

**Comment by shalako** [comment]
@CAFxX What do you mean by "middle boxes"?

**Comment by CAFxX** [comment]
@shalako network equipment that tracks TCP connections (e.g. firewalls)

**Comment by shalako** [comment]
It looks like Envoy supports what you're asking for:
- https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto.html#upstreamconnectionoptions
- https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/address.proto#envoy-api-msg-core-tcpkeepalive

We'll have to add support to Istio to configure it.
https://github.com/cloudfoundry/gorouter/issues/185

Closing in favor of Envoy
