### ISSUE TITLE
Unable to use multiple route services together

### ISSUE THREAD

**Issue by azuraka** [cloudfoundry/gorouter#186]
## Issue

I am unable to bind two route service instances with a single app. 

## Context

I want to use external authorization service and another API management service. The problem is both being route services, I am unable to bind both services to my CF App. Is there any alternative way to resolve this?

When I bind an App to two route-service-instance, I get an error message saying  "A route may only be bound to a single service instance".

**Comment by shalako** [comment]
Hello, only one route service is supported at this time.
The current workaround for complex use cases is to use a route service that supports internal chaining of operations. The Apigee route service for CF is an example of this.

We don't currently have a plan to support chaining of route services but I will record your request.

**Comment by azuraka** [comment]
Thank you for your reply :)
