### ISSUE TITLE
Allow operators to add custom handlers to the gorouter negroni chain

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/gorouter#187]
## Issue

Currently operators have no way to define custom functionality inside gorouter to comply with specific infrastructure/policy requirements.

## Context

The current typical workaround is to add such functionality in additional layer(s) in front of gorouter, but this approach has drawbacks:

- it increases deployment complexity
- it increases request latency
- it is not future-proof (e.g. it depends on SSL termination being done before gorouter, but this clashes with future features such as user-supplied TLS certificates and HTTP/2)

These issues would be lessened (or solved) by allowing operators to "extend" gorouter to include custom functionalities such as:

- inbound L7 traffic filtering (e.g. Host-header+source IP+source protocol based ACLs, traffic shaping)
- inbound traffic adaptation (e.g. adding/modifying headers)
- response transformation (e.g. custom error pages)
- custom log/metrics emission

## Possible Fix

One way to allow this is to define a set of "extension points" where operator-provided handlers can be added to the the negroni handler chain, and a way for operators to supply the handler implementations to add to each extension point.

There are a bunch of different ways to do something like this, each with pros and cons:
- build gorouter together with the operator-provided handlers
- build the operator-provided handlers as a go plugin, load the plugin when gorouter starts
- run the operator-provided handlers in a interpreted language embedded in gorouter
- run the operator-provided handlers in a separate process and proxy traffic through it

How many extension points and the exact semantics of each point will likely be open for debate. It may make sense to look at existing solutions and reuse concepts from them (e.g. [iptables chains](http://www.iptables.info/files/tables_traverse.jpg))

**Comment by shalako** [comment]
Are these use cases global or per route?

Our current recommended way to implement plugins is using route services. This enables implementation of these filters and transformations per route.

**Comment by CAFxX** [comment]
In our implementation these are global (e.g. we have multiple global shared domains, each one with different ACLs: our users pick the domain in base to the policies that traffic should be subject to)

Also route services can't be really used AFAIK to provide custom error pages when the gorouter emits the error (e.g. 404 for no route or no running instances, 502 for misbehaving backends, 400 for bad request)

**Comment by shubhaat** [comment]
Today route services can't be used for some use cases because they only work for routes mapped to running apps, but in our Istio-based routing subsystem we'll support routes (and associated routing rules/services) without apps.

As we don't plan on adding support for plugins or modifying the route services architecture for Gorouter, we'll capture your use cases for use with the Istio-based subsystem and close this.

If we understand you correctly, you would like admin control of global intermediating transformations in the data path. Thank you for providing examples of these.
