### ISSUE TITLE
Support HTTP/2

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/gorouter#195]
As pointed out in the [README](https://github.com/cloudfoundry/gorouter#http2-support), Gorouter does not support HTTP/2.

This means as a CF app developer, I am unable to leverage the significant benefits of the new protocol version. Likewise, any CF component whose communication paths pass through the Gorouter may not benefit from HTTP/2 either. By Gorouter not supporting HTTP/2, for example, both app developers and CF components cannot use gRPC, which is increasingly becoming the standard for microservice development.

/cc @cloudfoundry/cf-loggregator

**Comment by CAFxX** [comment]
gRPC support is one of the most commonly requested features even from our customers. Sure, they can use TCP routing but then they lose a whole lot of the gorouter out-of-the-box experience (path/hostname routing, logging, TLS termination, ...)

**Comment by jasonkeene** [comment]
Also, from what I understand, TCP routing is not enabled on all CF installations. That means CF components (such as loggregator) that need to work in every environment can not rely on TCP routing.

**Comment by jcheenatcode** [comment]
Now since node 8 is out, which has support for HTTP/2. We were planning to use it on our CF installations. This has a lot of good features that could be utilized for better UI experiences. Has this been considered as part of development for future quarters?

**Comment by jasonkeene** [comment]
It should be. CF should allow apps to use h2 without resorting to TCP routing.

**Comment by clncln1** [comment]
We are also waiting for this. Shouldn't that be fairly easy to implement since >= go 1.6 supports h2 transparently out of the box? Even without gRPC or content pushing, just enabling h2 to allow multiplexing would be great

**Comment by kitemongerer** [comment]
Any news on this issue? We are blocked on developing features for our application since we cannot use loggregator's new grpc client.

**Comment by shubhaat** [comment]
Closing this issue, we will keep the community updated via cf-dev as we build out the new routing subsystem. Proposal can be found here https://docs.google.com/document/d/1LgLY0g39fzpg1_4zTckbH1mOuuSKGvYwp2tkakoe9ys/edit
