### ISSUE TITLE
Instance routing should include in responses max(instance_idx)

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/gorouter#197]
Thanks for submitting an issue to `gorouter`. We are always trying to improve! To help us, please fill out the following template.

## Issue

When using [app instance routing](https://docs.cloudfoundry.org/concepts/http-routing.html#app-instance-routing), I would like to see in the response headers the biggest instance_idx currently in the routing table, something like:

```
X-CF-APP-INSTANCE-MAX: 8
```
to signify e.g. that the maximum instance index currently running is 8.

## Context

When using instance routing for the purpose of monitoring individual instances, it would be very helpful if the routers returned the number of instances of the application. This would allow active monitoring systems to opportunistically discover the number of running instances without having to poll the CC API.

Ideally, this number should reflect the number of *desired* instances, not the number of *running* instances. Since it may be difficult for gorouter to obtain the *desired* number of instances of an application (BBS should forward this information to gorouter somehow) this can possibly be approximated with the highest currently running instance index (monitoring systems can then apply some form of hysteresis to the values returned)

## Steps to Reproduce

Send a request with the header `X-CF-APP-INSTANCE: $APP_GUID:$APP_INSTANCE`

## Expected result

I receive in the response `X-CF-APP-INSTANCE-MAX: $APP_INSTANCE_MAX`, where `$APP_INSTANCE_MAX` is the instance index of the currently-running instance with the greatest instance index.

## Current result

No such header is returned

## Possible Fix

When a request that makes use of app instance routing is received by the gorouter, gorouter should scan the instance list for the specified app and return the index of the instance with the greatest instance index.

**Comment by shalako** [comment]
Seems reasonable. Would you send us a PR?

**Comment by CAFxX** [comment]
@shalako sent an initial PR, any feedback is welcome... as soon as the implementation is agreed upon, I will add some more internal tests and run the ATs

**Comment by KauzClay** [comment]
We are closing this issue due to the results of this [PR](https://github.com/cloudfoundry/gorouter/pull/198)
