### ISSUE TITLE
websocket should stream rather than copy whole message

### ISSUE THREAD

**Issue by TimMurnaghan** [cloudfoundry/gorouter#200]
## Issue

Gorouter is slow when handling large payloads in websocket messages

## Context

[provide more detailed introduction]

## Steps to Reproduce

Send a large (20-30MB) payload in a websocket message.

## Expected result

Message should be streamed to the app with minimal work on the router.

## Current result

Long delay between sending the message and it arriving at the application. Timeouts occurring.

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` Output Results

[if relevant, include a screenshot]

**Comment by charleshansen** [comment]
@TimMurnaghan 

Until you posted this, I thought GoRouter did stream messages on websockets. The relevant bit is a single line of code for us https://github.com/cloudfoundry/gorouter/blob/8128246bd730c55034bbb0fb855f20b7d0275a51/proxy/handler/request_handler.go#L234

I can look into this a bit more, but I'm not sure if we have any feasible options to improve the streaming. Do you have any suggestions yourself? @flawedmatrix do you think we can use `io.CopyBuffer` to force things to chunk without taking a big performance hit?

**Comment by TimMurnaghan** [comment]
@charleshansen Sorry for slow response - not monitoring here. And no - I suspect that the answer is some bigger refactoring/new apis  down in the go runtime. It probably should be a single line from the router's point of view. 
On the question of CopyBuffer - the router's performance is actually awful on large messages generally (same copying behaviour on http as well). You're relying on go to do the right thing but in the shared environment of the router memory behaviour is critical - so I would actually expect a huge performance boost from streaming properly.

Sadly, it's a dealbreaker for me so I'm actually giving up on CloudFoundry completely as I think that this (and other issues like no control over timeouts) make the gorouter too much of a non-controllable risk and that it's not yet a viable option for production.

**Comment by nouseforaname** [comment]
If too much off topic, please ignore..

@TimMurnaghan at the CF Summit in Basel a few guys hacked together a replacement for the router. The usecase was actually using https://letsencrypt.org/ on the fly for apps.. but what they did was replace the router with https://traefik.io/ and use nats route announcements to config traefic on the fly.. I do not see a reason why you would not be able to replace the routers if you wanted to..

**Comment by rosenhouse** [comment]
@nouseforaname you may be interested in [this design doc about replacing Gorouter with Envoy](https://docs.google.com/document/d/1VldkvgWPUh13o5RCNjSvzoPFhbY9BtLqBDdk2k0z9fw/edit).  The effort is in-flight.  You can track our progress towards the first milestone via [this "epic" label in Pivotal Tracker](https://www.pivotaltracker.com/epic/show/3747424).

**Comment by shalako** [comment]
We'll don't plan on any major refactors in Gorouter, as our long term strategy is to replace it with Envoy.   We'll make a note to explore Envoy support for streaming large payloads.
