### ISSUE TITLE
Steady memory increase

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/gorouter#204]
## Issue

We experience a steady memory increase of our gorouters over time. This seems currently not cause an issue. When the routers gets restarted it takes multiple days until the memory consumption is > 50%. 

![router_memory_usage](https://user-images.githubusercontent.com/16102838/34385653-8765ff9c-eb24-11e7-89a5-3b358aac94af.png)

## Context

We are using gorouter within `cf-deployment` ( v1.0.0, `routing-release` v0.166.0). SSL is not terminated on the gorouter. 

We cannot really correlate the first occurrence of this phenomenon with an update or change to the landscape. The memory increase also seems not to correlate with other metrics like e.g. `total_requests` or `total_routes`. The cpu usage is constantly < 20%.  

For an exemplary router with 35% memory usage, most memory seems to be consumed by `bufio.NewWriterSize`  `net/http.(*Transport).getConn`.  It looks similar for a router with > 80% memory usage. `netstat` and `lsof` do not indicate issues on the corresponding routers (e.g. too many open connections etc).

Attached goroutines and heap:
[gorouter_heap.txt](https://github.com/cloudfoundry/gorouter/files/1589403/gorouter_heap.txt)
[gorouter_goroutines.txt](https://github.com/cloudfoundry/gorouter/files/1589404/gorouter_goroutines.txt)

![profile001](https://user-images.githubusercontent.com/16102838/34386566-951022c6-eb29-11e7-8d03-d64ce24d0e85.png)

## Steps to Reproduce

We were not able to reproduce this on a test landscape.

## Expected result

Constant memory usage.

## Current result

Steady memory increase.

**Comment by pusherofbrooms** [comment]
We are seeing what looks like the same issue with increasing gorouter memory over time. It seems noticeable only on our highest traffic environment. This behavior started a couple of days after our upgrade from cf-release v280 to v283.

**Comment by shubhaat** [comment]
We have not investigated this, but would be interested to know if you are still seeing this issue?

**Comment by achawki** [comment]
No, at one day the high memory usage just stopped suddenly without any changes to the landscape (the number of requests stayed steady). We couldn't find out the root cause. 
Since then the issue didn't occur again.

**Comment by shalako** [comment]
That's great to hear. We'll close this issue then.
