### ISSUE TITLE
Keep Alive connections prematurely terminated by backend timeout code

### ISSUE THREAD

**Issue by univ0298** [cloudfoundry/gorouter#209]
## Issue

Keep alive connections are being closed because the backend timeout limit is not paying attention to whether a keep alive connection is alive because of ongoing re-use, or alive because of a long duration connection to a backend.

## Context

Keep alive will allow a connection to stay alive indefinitely, as long as it's used once every 90 seconds. 
However another feature, backend timeout maximum, is designed to cut off connections where a backend just takes too long to reply.
Unfortunately this second feature is colliding with keep alive, because the second feature sees a keep-alive connection as the same as a slow backend, and kills it, even if it is is mid-way through processing transactions and should have been kept alive.

This has a bad implication because it means that all keep alive transactions are terminated every n seconds, even if they are processing traffic. This leads to lots of 502 responses from the gorouter that should have been success responses.

## Steps to Reproduce

To reproduce this, be sure to use POST or PATCH requests. A GET request will not see the issue because the retry behavior "saves" the transaction and masks the issue. But POST/PATCH are not retry-able so will see it.
Also, a slow backend application makes it easier to recreate because the issue is seen by having an in-flight transaction get interrupted. So a simple ten second sleep in the app is helpful.

With that in place, it can be easily reproduced by configuring a request_timeout_in_seconds value of 30 seconds, and a high number of max_idle_connections (say 49000). Once this is done, send a POST request to an app. That will cause a connection from gorouter to app to be created and the app will reply (after 10 seconds if you have a sleep 10). Then 25 seconds after the first request was sent, send another one. You will see a 502 response code after 5 seconds (as the total test time hits 30 seconds).

Some more details of the scenario:
1.    A new connection established
2.    I/O Deadline set to Now()+endpoint_timeout (e.g. Now + 30s)  [see https://github.com/cloudfoundry/gorouter/blob/master/proxy/proxy.go#L131]
3.    Keep alive remains enabled for this connection
4.    Many requests occur over time on the Keep alive connection, still keeping it open
5.    A POST/PATCH request occurs on the kept alive connection close to the initial I/O deadline timeout set by (2)
6.    Before the response can be read from the request, the I/O deadline timeout expires and the connection is closed
7.    Since it was an outstanding POST/PATCH, the request is not retried and a 502 is returned to the caller

## Expected result

A keep alive connection should live indefinitely, as long as it's re-used within 90 seconds. No 502 error should be seen

## Current result

As explained above, transactions are failing.

## Possible Fix

https://cloudfoundry.slack.com/archives/C05586PBX/p1519324304000384
swetha :I believe the fix is to remove the deadline after a backend has sent a response

## `name of issue` Output Results

N/A

**Comment by shalako** [comment]
Prioritized for engineering.

**Comment by shalako** [comment]
Had a chat about this with Max and asked if IBM would contribute a PR for the fix, as the CF Routing team is heavily focused on the Istio integration. I recommended grabbing @aaronshurley in the CF Slack #routing channel and coordinating a chat about how this might be solved.

**Comment by shalako** [comment]
Closing as this was fixed with merging #211. 
We'll cut a routing-release next week with the change, and it will be included in the next cf-deployment after that.
