### ISSUE TITLE
development on mac: error reading file descriptor from /proc

### ISSUE THREAD

**Issue by samzilverberg** [cloudfoundry/gorouter#210]
## Issue

https://github.com/cloudfoundry/gorouter/blob/master/main.go#L116
## Context

https://github.com/cloudfoundry/gorouter/blob/master/main.go#L178-L182

starting gorouter calls initializeFDMonitor function that tries to monitor a file under /proc.
but mac doesnt have this folder, more details here:
https://superuser.com/questions/631693/where-is-the-proc-folder-on-mac-os-x

[provide more detailed introduction]

## Steps to Reproduce

using a mac system:
- get the code, as advised, from routing-release
- cd into gorouter src
- `go build && go install`
- run the gorouter binary

## Current result

lots of log messages from gorouter not being able to read from /proc, such as:
```
{"log_level":3,"timestamp":1519985287.180445,"message":"error-reading-filedescriptor-path","source":"gorouter.stdout.FileDescriptor","data":{"error":"open /proc/73909/fd: no such file or directory"}}
```
and
```
{"log_level":1,"timestamp":1519985291.6113324,"message":"exited","source":"gorouter.stdout.FileDescriptor","data":{}}
```

## Possible Fix

- EITHER abstracting monitoring FD based on OS
- OR lettins users disable monitoring FD via some flag (env var?)
- OR stating thats there is 0 support for mac

**Comment by samzilverberg** [comment]
i was able to continue developing on mac by changing source code to NOT instantiate the file descriptor monitor.
but this is a very hacky solution...

**Comment by Nino-K** [comment]
Having a flag to disable the `fdMonitor` based of the runtime seems like a reasonable approach, however this requires a bigger team discussion to see if the plan is to support darwin at all. We will mark this as requires team discussion.

**Comment by KauzClay** [comment]
We are currently focusing efforts on Istio/Envoy integration in CF, so we won't be able to get to this any time soon. We would be happy to review a PR!
