### ISSUE TITLE
gorouter closing connection to client before writing the whole response body

### ISSUE THREAD

**Issue by samzilverberg** [cloudfoundry/gorouter#212]
## the issue:

- client side has an open upstream
- server reads part of the upstream body and determines it doesnt want to continue
- server responds with response with a non-smallish body (example 20k-50k chars) and a connection:close header.
- server closes the conn from its side AFTER finishing writing the full responds body
- client upstream is still in progress
- THE BUG: gorouter throws some err because it cant write the client upstream to server anymore, and closes all related tcp connection, BEFORE writing the whole server's response to the client.

so the client receieves only partial (or none) response from the server.

## example scenario for bug

we've found this bug while implementing file upload.
we wanted the server to limit file size to 2mb, without having to read the whole request body from client (which could just as well be 1000mb).
so the server read up to 2mb and then responded with an err code and some meaningful response body (json, around 1k-2k chars).
locally everything worked but once uploaded to a cloudfoundry environment, with gorouter in the middle, the problems started appearing.

## cause of problem

debugging we've found the problem in gorouter code, in:

https://github.com/cloudfoundry/gorouter/blob/master/proxy/round_tripper/proxy_round_tripper.go#L100-L106

these changes were introduced as a fix for https://github.com/cloudfoundry/gorouter/issues/130
in commit: https://github.com/cloudfoundry/gorouter/commit/055fee9a69e8dc5fc9acb94e5790ee17df5dd365

when commenting out the `if request.Body != nil {...}` clause our issue doesn't appear.
were not confident enough introducing a PR that would fix our issue while still solving the other one, perhaps the original commiters are still around and can take a look?

**Comment by rosenhouse** [comment]
Looks a lot like https://github.com/cloudfoundry/routing-release/issues/98.  I'm going to go close that one in favor of this.

---

I'll admit I don't know what the right behavior is here.  Must we guarantee that the complete server response is sent before closing the client connection?

It would be helpful if we could see a relevant HTTP RFC or documented behavior of other HTTP reverse proxies, so we can understand what is right.  (In Envoy, for example, [the TCP proxy does an immediate close](https://github.com/envoyproxy/envoy/issues/1189#issuecomment-311988350).  But HTTP may be different).

---

If you're looking to make a PR, you can't just leave response bodies unclosed -- that would leak file descriptors.  The better thing would be to block closing the downstream response body until the upstream (server) response has closed.  I don't know how to do that off the top of my head.

**Comment by thausler786** [comment]
@rosenhouse I notice that you closed this issue in favor of cloudfoundry/routing-release#98..  However, you also closed that issue in favor of this one.  This was probably a mistake?

We also encountered this problem, with the same symptom of the app's HTTP response being truncated at about 2MB. Specifically:

- When the app is `curl`ed from outside the router -- from our local workstation, for example -- the response is truncated to ~2MB. The response is truncated 100% of the time when using HTTPS, and ~80% of the time using HTTP. 
- When the app is `curl`ed from the container on which the app is hosted using the container's local IP address, the response is _not_ truncated.
- When SSHed into a router instance, when the app is `curl`ed from the router using the app's IP address, the response is _not_ truncated.
- When SSHed into a router instance, when the app is `curl`ed through the router process using the `Host` header and the router's local IP address, the response is truncated.

**Comment by rosenhouse** [comment]
@thausler786 is your server closing the connection before the client body is fully uploaded?  I hadn't seen that in your previous bug report.

**Comment by samzilverberg** [comment]
@rosenhouse i took a look at http rfc's (both old one 2616 and new one 7230) and it was very hard to find a clear answer to this question.

https://tools.ietf.org/html/rfc7230 was more useful.

reverse proxies are refered to as "gateway" and are said they should behave exactly like an "origin server" (that is, the "target" server of the original request).

later on in 6.3 Persistence it says
>A server MUST read
   the entire request message body **OR** close the connection after sending
   its response, since otherwise the remaining data on a persistent
   connection would be misinterpreted as the next request.

notice i emphasized the OR.
to me reading this it means that the reverse proxy should write the whole response to client before closing. but as its not directly stated that way i can see how one could argue about this.

the other sections i found informative in regards to this problem are:
section 6.6 about how to Tear-Down a request
and 6.1 connection 

before thinking of making a PR, i'd like to see if maybe someone from your team knows about 
https://github.com/cloudfoundry/gorouter/commit/055fee9a69e8dc5fc9acb94e5790ee17df5dd365
as stated before, the problem originates from this commit.
if we comment this out recompile and run, everything works.
suggesting maybe the suggested defer solution is not enough.
maybe someone from your team knows more about the original problem and can suggest a different solution? one which will not introduce this issue?

**Comment by zlav** [comment]
Related information that might be helpful
https://github.com/golang/go/issues/11745#issuecomment-123555313

**Comment by rosenhouse** [comment]
I'm pretty sure that [this tracker feature story](https://www.pivotaltracker.com/story/show/160355112) is the fix to this issue.

We've prioritized that story for the engineering team.

**Comment by utako** [comment]
Hi @samzilverberg,

Since [this story](https://www.pivotaltracker.com/story/show/160355112) is currently prioritized and captures this issue, I'm going to close this to reduce duplication in our backlog. If that story does not fit your needs, please feel free to reopen another issue.

Thanks,
@utako, CF Routing Team
