### ISSUE TITLE
Gorouter - 502 bad gateway error

### ISSUE THREAD

**Issue by xavierW** [cloudfoundry/gorouter#218]
Thanks for submitting an issue to `gorouter`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Recently,i have a Java application, this is a batch application, it will continue to send a post request to the server app, but every once in a while, it triggers a 502 event, the batch application has been suspended.

I have about 10,000 urls on my side, and the default is the endpoint_timeout of 900

## log info

```
{"log_level":3,"timestamp":1528944202.5672262,"message":"endpoint-failed","source":"vcap.gorouter","data":{"route-endpoint":{"ApplicationId":"138e94c2-7ea9-47ff-9273-384b45487504","Addr":"container_ip:61048","Tags":{"component":"route-emitter"},"RouteServiceUrl":""},"error":"read tcp route_ip:37322->container_ip:61048: i/o timeout"}}
```

## Context

route-release 0.174.0

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` Output Results

[if relevant, include a screenshot]

**Comment by shubhaat** [comment]
Hi @xavierW, 

Are you able to look at the app logs and the gorouter logs at the time you get a 502? It might point to what might be going on. 

From the log message you have posted, it looks like the app might be timing out with a i/o request. 

Regards,
Shubha

**Comment by xavierW** [comment]
Hi @shubhaat ,

the app logs:

```
2018-6-15 10:3:44 [RTR/13]  app.domain.io - [2018-06-15T02:03:37.128+0000] "POST /rmi.do HTTP/1.1" 502 26788 67 "-" "Java/1.7.0_80" "xx.1.2.xxx:17375" "xx.xx.xxx.34:61004" x_forwarded_for:"xx.0.xx.xxx, xx.1.2.251" x_forwarded_proto:"http" vcap_request_id:"4c567a3f-c063-45bd-5d47-ab0180a58604" response_time:7.230636289 app_id:"138e94c2-7ea9-47ff-9273-384b45487504" app_index:"0" x_b3_traceid:"3d83290acf524d25" x_b3_spanid:"3d83290acf524d25" x_b3_parentspanid:"-"
```
It happens every 10 to 15 minutes, and i set the jboss server request timeout 40min.

**Comment by Nino-K** [comment]
@xavierW can you also check gorouter's `access_logs` at the time when `502` takes place, just wondering if there might me something more interesting in there?

Thanks, 
@nhsieh & Nino

**Comment by shubhaat** [comment]
@xavierW - we are closing this issue due to age. Feel free to reopen if this is still an issue for you.
