### ISSUE TITLE
Zipkin tracing no longer sets X-B3-ParentSpanID

### ISSUE THREAD

**Issue by jblackman** [cloudfoundry/gorouter#221]
## Issue

Prior to commit fa255ae022323db12782a83bc02d1f3d13411685 the Zipkin middleware set the X-B3-ParentSpanId header variable. In the current code this is no longer the case.

The original code did not have explicit tests for this, which is how it probably slipped through.

## Context

According to the [CF documentation](https://docs.cloudfoundry.org/concepts/http-routing.html#zipkin-headers), if both the X-B3-TraceId and X-B3-SpanId headers are set, then a new X-B3-SpanId header will be generated and X-B3-ParentSpanId header will be set to the original SpanId.

This feature allows developers to trace the application call chain for a given trace, so it can be surprisingly useful in complex microservice architectures.

## Steps to Reproduce

1. Push a "service" application (zipkin-svc, say)
2. Push a "main" application that will call the first one (zipkin-main, say)
3. Call the "main" application
4. Examine the headers for each

Here are the test apps I used to reproduce this issue:

**Gemfile**
```ruby
source 'https://rubygems.org'

gem 'sinatra'
gem 'httparty'
gem 'json'
```

**Service application**
```ruby
require 'sinatra/base'
require 'json'

class App < Sinatra::Base
  get '/' do
    {
      app: 'zipkin-svc',
      headers: {
        'X-B3-TraceID' => request.env['HTTP_X_B3_TRACEID'],
        'X-B3-SpanID' => request.env['HTTP_X_B3_SPANID'],
        'X-B3-ParentID' => request.env['HTTP_X_B3_PARENTID'],
      }
    }.to_json
  end
end

run App.new
```

**Main application**
```ruby
require 'sinatra/base'
require 'httparty'
require 'json'

abort 'SERVICE_URL not specifed' unless ENV['SERVICE_URL']

class App < Sinatra::Base
  get '/' do
    headers = {
      'X-B3-TraceId' => request.env['HTTP_X_B3_TRACEID'],
      'X-B3-SpanId' => request.env['HTTP_X_B3_SPANID'],
    }
    rv = HTTParty.get(ENV['SERVICE_URL'], headers: headers)
    svc_result = JSON.parse(rv.body)
    {
      app: 'zipkin-main',
      headers: headers,
      service: svc_result,
    }.to_json
  end
end

run App.new
```
## Expected result

The "service" headers should be populated as in the example below (X-B3-SpanID is different from the trace id and X-B3-ParentID is set to the "main" span id):

```json
{
  "app": "zipkin-main",
  "headers": {
    "X-B3-TraceId": "7b867f8d3433b203",
    "X-B3-SpanId": "7b867f8d3433b203"
  },
  "service": {
    "app": "zipkin-svc",
    "headers": {
      "X-B3-TraceID": "7b867f8d3433b203",
      "X-B3-SpanID": "abcdefg123456678",
      "X-B3-ParentID": "7b867f8d3433b203"
    }
  }
}
```

The logged headers should match this expectation as well.

## Current result

The "service" headers are identical to the "main" ones and X-B3-ParentID is not set.

```json
{
  "app": "zipkin-main",
  "headers": {
    "X-B3-TraceId": "7b867f8d3433b203",
    "X-B3-SpanId": "7b867f8d3433b203"
  },
  "service": {
    "app": "zipkin-svc",
    "headers": {
      "X-B3-TraceID": "7b867f8d3433b203",
      "X-B3-SpanID": "7b867f8d3433b203",
      "X-B3-ParentID": null
    }
  }
}
```

The logged headers reflect the above.

## Possible Fix

The original code looks fairly sane, so I'm happy to create a PR that rolls the functionality forward if desired.

**Comment by shalako** [comment]
Hello, this change was intentional. Please see https://github.com/cloudfoundry/routing-release/issues/110 for the reasoning.

**Comment by jblackman** [comment]
It seems a shame to remove useful functionality. So, should the CF documentation be changed to match the current behaviour, then?

**Comment by shalako** [comment]
Hello @jblackman 
I you found the previous behavior useful, please add your comments in cloudfoundry/routing-release#110.

We do intend to fix the documentation.

**Comment by jblackman** [comment]
Comment added. Many thanks for the update!
