### ISSUE TITLE
Cannot access cf app: 502 Bad Gateway

### ISSUE THREAD

**Issue by zhanggbj** [cloudfoundry/gorouter#222]
## Issue

Cannot access cf app: 502 Bad Gateway. Registered endpoint failed to handle the request.

## Context

I'm running Cloud Foundry on K8s, `cf push app` complete successfully, but when to access the app `curl app.${domain}`, it returns `502 Bad Gateway`. Here are some logs and debug info. Would you please help take a look? Any suggestions. Thanks!

- **app is running**
```
$ cf curl /v2/apps/c18b3c37-0e26-4e34-a648-b66106995bd3/stats
{
   "0": {
      "state": "RUNNING",
      "isolation_segment": null,
      "stats": {
         "name": "node",
         "uris": [
            "node.bcf.us-south.containers.appdomain.cloud"
         ],
         "host": "172.30.228.208",
         "port": 61001,
         "uptime": 482,
         "mem_quota": 1073741824,
         "disk_quota": 1073741824,
         "fds_quota": 16384,
         "usage": {
            "time": "2018-07-19T14:46:14+00:00",
            "cpu": 0.0,
            "mem": 41603072,
            "disk": 51843072
         }
      }
   }
}
192:~ $ cf ssh node
vcap@335eee6a-2ea3-4861-7958-76ac:~$ netstat -apn|grep 8080
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 10.38.0.2:36052         10.38.0.2:8080          TIME_WAIT   -
tcp        0      0 10.38.0.2:36156         10.38.0.2:8080          TIME_WAIT   -
tcp6       0      0 :::8080                 :::*                    LISTEN      68/node
```

- **access.log in gorouter**
```
node.bcf.us-south.containers.appdomain.cloud - [2018-07-19T14:38:52.245+0000] "GET / HTTP/1.1" 502 0 67 "-" "curl/7.47.0" "127.0.0.1:55934" "172.30.228.208:61001" x_forwarded_for:"9.37.192.205, 10.94.5.46, 127.0.0.1" x_forwarded_proto:"http" vcap_request_id:"3a952ac2-ff4b-4257-6781-4a0f7d0339ed" response_time:0.001296569 app_id:"c18b3c37-0e26-4e34-a648-b66106995bd3" app_index:"0" x_b3_traceid:"5d5313365552062f" x_b3_spanid:"5d5313365552062f" x_b3_parentspanid:"-"
```
- **Diego cell iptables as below**
```
-A w--instance-gm8o38r5pg8 -d 172.30.228.208/32 -p tcp -m tcp --dport 61001 -m comment --comment 335eee6a-2ea3-4861-7958-76ac -j DNAT --to-destination 10.38.0.2:8080
-A w--instance-gm8o38r5pg8 -d 172.30.228.208/32 -p tcp -m tcp --dport 61002 -m comment --comment 335eee6a-2ea3-4861-7958-76ac -j DNAT --to-destination 10.38.0.2:2222

```

## Steps to Reproduce

$ cf push app
$ cf curl app.domain

## Expected result

access app successfully.

## Current result

get 502 Bad Gateway

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` Output Results

[if relevant, include a screenshot]

**Comment by shalako** [comment]
Hello,
We don't test with CF running as containers on K8s so we can't promise that this works.

In general, a 502 indicates that Gorouter knows about about the route but cannot establish a TCP connection to the app instance.

I would suggest logging into the Gorouter container and confirm that you can make a request directly to 172.30.228.208:61001.

**Comment by zhanggbj** [comment]
@shalako, thanks for your quick reply. 
It worked well in my cluster and I can push and access my app, until I put an envoy proxy aside with gorouter.

From the gorouter container, it cannot access the address. Is there any suggestion for further debugging? Thanks.

```
router/20704452:/# curl 172.30.228.208:61001
curl: (56) Recv failure: Connection reset by peer
```

**Comment by shalako** [comment]
Why do you have an Envoy? Is it the sidecar managed by Diego?

**Comment by zhanggbj** [comment]
@shalako 
It's an envoy sidecar managed by  [Istio](https://istio.io/), as we are running CF on K8s, so gorouter turns to a K8s service and we would like to manage this service using Istio. 

And there's another error log in gorouter, seems the tcp connection fail to create but not sure why...
[2018-07-20 07:43:25+0000] {"log_level":3,"timestamp":1532072605.9103882,"message":"backend-endpoint-failed","source":"vcap.gorouter","data":{"route-endpoint":{"ApplicationId":"c18b3c37-0e26-4e34-a648-b66106995bd3","Addr":"172.30.228.208:61001","Tags":{"component":"route-emitter"},"RouteServiceUrl":""},**"error":"read tcp 172.30.146.26:41866->172.30.228.208:61001**: read: connection reset by peer"}}

**Comment by shalako** [comment]
Cloud Foundry has not been tested to run in such a configuration. Gorouter does not use Istio for service discovery; it uses NATS. Gorouter expects to be able to connect to the application container via the Diego Cell host (a VM). In an environment where gorouter and the application are running in containers, we expect gorouter to connect to the application container directly. If there are other components in the data path, you must figure out how to facilitate Gorouter reaching the app container.

**Comment by zhanggbj** [comment]
@shalako Thanks a lot for the detailed information, I'll continue the investigation. Will close this issue for now.
