### ISSUE TITLE
implement "b3 single" header format

### ISSUE THREAD

**Issue by adriancole** [cloudfoundry/gorouter#224]
## Issue

We should permit at least parsing the more compressed "b3" header format, if not making it possible to propagate it downstream.

ex.  `b3: 4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-1`

This is the same format as will be used in the w3c tracestate

## Context

Details are here: https://github.com/openzipkin/b3-propagation/issues/21

Example implementation is here: https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/B3SingleFormat.java https://github.com/openzipkin/brave/blob/master/brave/src/test/java/brave/propagation/B3SingleFormatTest.java

**Comment by KauzClay** [comment]
We're currently focusing our efforts on integrating Istio and Envoy into CF so we likely won't be able to prioritize this anytime soon. We'd be happy to review a PR!

/cc @shalako for awareness

**Comment by jcchavezs** [comment]
I am working on this now.
