### ISSUE TITLE
Session stickiness fails when routed via Spring Cloud Gateway

### ISSUE THREAD

**Issue by karthiksnair** [cloudfoundry/gorouter#225]
Thanks for submitting an issue to `gorouter`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Request routed to an app via Spring Cloud Gateway deployed in PCF, fails to do sticky sessions despite having JSESSIONID.

## Context

Gorouter ensures sticky sessions (same app instance), for requests from browser to application deployed on PCF, The application uses JSESSIONID cookie to achieve this.

However, when the requests are routed via a Spring Cloud Gateway application, the session stickiness is not ensured by Go router. This happens when using ribbon with service registry (with route registration) and also when using public route URLs. 

Session replication is enabled via PCC and java build pack.
cf create-service p-cloudcache small-plan my-session-replication -t session-replication

Reason to use a gateway application is that we have few other applications (such as static webs) to which the requests from browser will be routed based on paths and other criteria. We would be also implementing a lot of cross cutting concerns in this layer such as tracing, security, throttling, etc.

## Steps to Reproduce
1. Create a spring boot war application and deploy it to Tomcat via Java build pack.
     1.a) Create a index.jsp page which makes some ajax calls to the app. 
     1.b) Use a filter within the application to validate session on request. 
     1.c) If session is null throw exception - landed in a different node. (you can also see the cf logs to confirm the instance)
      1.d) push application to cloud foundry and bind route myapp.app.pcfone.urorg.com
      1.e) Bind PCC cache with session replication
      1.e) scale the instances of the app.
2. Create a spring cloud gateway application (boot jar) and push it to PCF
    2.a) use configuration to route all requests to myapp.app.pcf.urorg.com
or
    2.b) use configuration to route all requests to lb://myapp
    2.c) push app to cloud foundry and bind route mygateway.app.pcfone.urorg.com
3.  If you access myapp.app.pcf.urorg.com/index.jsp, you will find that the subsequent ajax requests are routed to the same app instance. You identify this from response headers or CF logs.
4. However, if you access mygateway.app.pcfone.urorg.com,  you will find that the subsequent ajax requests are routed to various  app instances and the session is unavailable on other instances. 

## Expected result

Expected result - sticky session to be used for all requests even when the app URL is routed via the gateway app.

## Current result

Sticky session is not honoured by GoRouter if the client is not a browser but an app deployed on cloud foundry.

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` Output Results

[if relevant, include a screenshot]

**Comment by karthiksnair** [comment]
We are finding that the JSESSIONID and VCAP_ID cookies from the tomcat based application is being overridden by the ones generated by and for the Spring Cloud Gateway app.  We are trying to change the cookie name now.  There are other bunch of headers the gateway sets. 

1. Is there a possibility that Go_Router prefixes app_name to the JSESSION_ID and VCAP_ID so that apps along the chain do not override each others cookies.
2. Is there a way to instruct spring cloud gateway to be unobtrusive and allow developers to enable features selectively?

**Comment by KauzClay** [comment]
> Is there a possibility that Go_Router prefixes app_name to the JSESSION_ID and VCAP_ID so that apps along the chain do not override each others cookies.
GoRouter should not be prefixing an app name to the JSESSION_ID or VCAP_ID, expected behavior is documented here:  https://docs.cloudfoundry.org/concepts/http-routing.html#sessions

If problems persist with this environment, we recommend contacting Pivotal support as it pertains to PCF/Spring.

**Comment by shalako** [comment]
We recommend going through Pivotal Support for this issue, as we are an OSS team and don't have access to environments with PCC, service registry, Spring Cloud Gateway, etc.

**Comment by hanscrg** [comment]
@karthiksnair, do you have the solution yet? Does change cookie name work? Change should be in Cloud Gateway tie or application tie (behind gateway)?
