### ISSUE TITLE
Go router has 16KB header limit

### ISSUE THREAD

**Issue by alexmora81** [cloudfoundry/gorouter#240]
Thanks for submitting an issue to `gorouter`. We are always trying to improve! To help us, please fill out the following template.

## Issue

When using custom header and passing a SAML token greater than 16kb the header gets truncated
## Context

Have a cluster of apps that need to share SAML authentication. Per design, a SAML token is passed to receiving API's using a custom header SAML_RESP. If the token is larger than 16kb the header gets truncated

## Steps to Reproduce

Send a header larger than 16kb and examine on the receiving end. We'll see that the header is truncated

## Expected result

It would be nice if there wasn't a limit or at least if the limit was increased

## Current result

Header gets truncated therefore we received an incomplete token

## Possible Fix
Increase the hard limit of 16kb

## `name of issue` Output Results

[if relevant, include a screenshot]

**Comment by shalako** [comment]
We would welcome a PR for this; please include a PR to github.com/cloudfoundry/routing-release to support a configurable manifest property.

Our team is currently focussed on building the Istio Pilot and Envoy based routing tier and we are not likely to prioritize doing this ourselves in the near term, but we will prioritize review and merging of a PR.

**Comment by utako** [comment]
Closing this issue, as we are not planning on prioritizing this work. As @shalako said, we welcome a PR to support this. Feel free to reference this issue in doing so.
