### ISSUE TITLE
Route not found 404s should not be cached

### ISSUE THREAD

**Issue by richardTowers** [cloudfoundry/gorouter#243]
## Issue

gorouter doesn't return a Cache-Control header for 404s. This can cause issues for sites that sit behind HTTP caches.

## Context

If all of the apps serving a particular app fail their healthcheck, gorouter will respond with a 404.

If there are caching proxies in front of gorouter these may decide to cache this 404 when the applications become healthy again.

This can result in the undesirable situation that an application that has a few seconds of downtime can end up with a cached 404 for hours (depending on the cache configuration).

## Steps to Reproduce

```
curl -v http://some-gorouter-route-that-does-not-exist.localhost:8080
```

## Expected result

`Cache-Control: no-cache, no-store`

## Current result

No `Cache-Control` header.

## Possible Fix

Add `Cache-Control: no-cache, no-store` to route-not-found 404 responses. Leave headers for application 404s as they are.

**Comment by shubhaat** [comment]
Hi @richardTowers , 

That seems like a valid concern, can you tell us a bit more about the impact you are seeing in your CF deployments from this. I am looking for more information in terms of impact, to be able to prioritize this. 

Also we are open to PRs and recommend making a PR to us, we will be able to prioritize merging PRs from the community. 

Routing team

**Comment by richardTowers** [comment]
Hi @shubhaat ,

Some of our CF applications are fronted by caches like cloudfront and fastly. The majority of the time everything is just fine, but if you get very unlucky and the app is unregistered while the cache is cold you can end up with the 404 page in the cache.

It is already possible for operators to work around this by mapping a default route with caching disabled.

I think it should be pretty low-risk to put a Cache-Control header disabling caching on the response in the no-route case though, and have the default behaviour be less risky.

I'll have a look at the code and send you a PR if I can.

**Comment by bruce-ricard** [comment]
Hi @richardTowers.

> This can result in the undesirable situation that an application that has a few seconds of downtime can end up with a cached 404 for hours (depending on the cache configuration).

What if instead of setting the `cache-control` header to `no-cache`, we set it to `public` with a `max-age` of a couple seconds? This would still allow the cache to protect the gorouter to some degree, while not having the end user wait for hours.

**Comment by tlwr** [comment]
I work on the same team as @richardTowers so have the same context. Sorry for the slow response.

`Cache-Control: public,max-age=2` is a good solution for both users and gorouter.

What are your thoughts on this being set for other pages gorouter, e.g. whenever serving `502`s.

**Comment by ameowlia** [comment]
Hi @tlwr and @richardTowers, 

We think it's reasonable to have this cache-controller header when the gorouter returns 4XX and 5XX. Pinging our PM @adobley, to see if this sounds reasonable to him.

If you could update your PR with this `Cache-Control: public,max-age=2` header instead of the `no-cache` header, that would be great.

Thanks, 
@ameowlia and @bruce-ricard, CF Networking Program Members

**Comment by tlwr** [comment]
Hi, @ameowlia - thanks, I have updated #244 accordingly

**Comment by adobley** [comment]
This sounds reasonable to me. Happy to move forward with that strategy.
