### ISSUE TITLE
Session Persistence - JSESSIONID Only?

### ISSUE THREAD

**Issue by aristotelesneto** [cloudfoundry/gorouter#26]
Hi Guys,

Is there a reason for only enabling sticky sessions based on JSESSIONID?

https://github.com/cloudfoundry/gorouter/blob/master/proxy/proxy.go#L23

That implies Apps sitting behind the router are Java based, otherwise the app developer needs to set a cookie by that name explicitly, instead of allowing things like PHPSESSID, sid, to be automatically picked up.

Anything against making this a configurable regex?

**Comment by varun7447** [comment]
Is this support added to the CLI? Can i pass the sticky session using `-s <<COOKIE NAME>>`?

**Comment by shalako** [comment]
No, this was never implemented. 

However, sticky sessions are still supported. See our docs here: http://docs.cloudfoundry.org/concepts/http-routing.html#sessions

**Comment by varun7447** [comment]
I have custom cookie (Test.cookie). Can I create JSESSIONID with the Test.cookie?

**Comment by varun7447** [comment]
Looks like I was able to create one. Is the cookie always have to be named as JSESSIONID? Can I name the cookie name as APP.COOKIE.YES?

**Comment by evasanthan** [comment]
I just wanted to understand about queries on JSESSIONID. What i understood was, the usage of HTTPSession is an anti pattern for Cloud migration as sessions are ephemeral in the Cloud environment. By default, JSESSION ID from Servlet, converts to the HTTPSession as a background process.  Incase If any application uses JSESSION ID, Are you saying that JSESSION ID is not an anti pattern for Cloud migration?  For example, JSP  page uses the JSESSION ID  how it works when scaling the application in  the Cloud Foundry?  Is that possible to deploy the JSESSION ID feature into CLoud Foundry PAAS environment without making any changes in the Code?  Or as mentioned the documentation,Whether VCAPID needs to be appended  to maintain the JSESSION ID call on the respective  server. Please clarify or provide some samples to understand more  on this.  Thanks in Advance.
