### ISSUE TITLE
Implement W3C Trace Context headers

### ISSUE THREAD

**Issue by ecourreges-orange** [cloudfoundry/gorouter#260]
## Issue
Feature Request

## Context

gorouter supports Zipkin b3 headers, which propagates only to applications supporting Zipkin b3 headers. https://docs.cloudfoundry.org/concepts/http-routing.html#zipkin-headers

There is now since August 2019 proposed standard headers "traceparent" and "tracestate" which can be used and will be used by all tracing frameworks from now on. https://www.w3.org/TR/trace-context/

It would be great for backwards compatibility to have support for both Zipkin _and_ W3C Trace Context, or more simply one or the other if you don't have time to for the dual logic complexity.

If supporting both, the configuration could look like this:
```
properties:
  router:
    tracing:
      enable_zipkin: true
      enable_w3c: true
      default: w3c

```
The logic could be the following if the default selected is w3c:
- If no trace headers are present in the request, the Gorouter generates values for the w3c headers and inserts the headers into the request forwarded to an app. These values are also found in the Gorouter access log message for the request: traceid and spanid.
- If the X-B3-TraceId and X-B3-SpanId HTTP headers are present in the request, the Gorouter creates corresponding w3c headers out of them. In addition to these trace and span IDs, the Gorouter access log message for the request includes parentspanid.
- If the traceparent and tracestate HTTP headers are present in the request, the Gorouter forwards them unmodified. In addition to these trace and span IDs, the Gorouter access log message for the request includes parentspanid.

Thank you

**Comment by tlwr** [comment]
I started this in https://github.com/cloudfoundry/gorouter/pull/261

Currently implemented so that:

- Zipkin headers work
- W3C headers work

Where they do not interact with each other at all

**Comment by adobley** [comment]
Hello @ecourreges-orange! 

I've merged the PRs from @tlwr (cloudfoundry/routing-release#160 and cloudfoundry/gorouter#261) and the change is making its way through our pipeline. 

I'll let you know here when it's ready in a release to be consumed. You can also follow the tracker stories of the PRs to see when they're accepted.

If you're able to test out the current `develop` branch of `routing-release` we'd love early feedback on our changes :D 

Thanks!

**Comment by KauzClay** [comment]
Hi @ecourreges-orange !

@tlwr 's changes were merged in and have been part of routing release since 0.196.0.

I hope the changes are working for you. Since it has been released for a while now, I am going to close this issue. Please feel free reopen if you have more comments/concerns.

Thank you!
@KauzClay , CF Networking
