### ISSUE TITLE
Doc Update: X-CF-APP-INSTANCE response headers should be documented

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/gorouter#265]
## Issue

Since we recently changed the behavior on both invalid X-CF-APP-INSTANCE header and missing instance denoted by said header to return status 400, it has become difficult for users to distinguish the two.

We are already emitting a `X-Cf-Routererror` header with different values for each state but it is not documented in the dev guide yet.

## Context

As a user I want to be able to distinguish between a missing app instance (`unknown_route`) and a bad instance header (`invalid_cf_app_instance_header`), so I can write code that reacts differently for each state without having to string-parse the response body which is unsafe.

## Steps to Reproduce

Open dev guide at https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#surgical-routing

Open docs at https://docs.cloudfoundry.org/concepts/http-routing.html#app-instance-routing

Open gorouter docs at https://github.com/cloudfoundry/gorouter#headers

## Expected result

Documentation should mention both return code 400 on error as well as the response header `X-Cf-Routererror` with possible values `unknown_route` and `invalid_cf_app_instance_header`.

## Current result

Documentation only mentions return code 400 on error.

## Possible Fix

Add a small section that explains the response headers.

**Comment by KauzClay** [comment]
Hey @domdom82,

Thanks again for pointing out these discrepancies. Here are the proposed changes:

https://github.com/cloudfoundry/gorouter/commit/06e3165fd0952e8f4662fe6d4046ee85dc5e5f29

https://github.com/cloudfoundry/docs-cloudfoundry-concepts/pull/134

https://github.com/cloudfoundry/docs-dev-guide/pull/392

If you have questions or concerns, please let us know!

Thanks!
Clay and @adobley , CF Networking Program

**Comment by domdom82** [comment]
Hi @KauzClay  thanks for the fix! I noticed a small issue in gorouter readme.md with the change:

The sentence ´Usage of the X-Cf-App-Instance header is only available for users on the Diego architecture´ is now duplicated at the end of the section. https://github.com/cloudfoundry/gorouter#headers

**Comment by KauzClay** [comment]
ohp, thanks for pointing that out! fixed it here https://github.com/cloudfoundry/gorouter/commit/90cbd52b6fd5f2f40803ad861d2378c8684dce43
