### ISSUE TITLE
Intent to support HTTP/2

### ISSUE THREAD

**Issue by MerricdeLauney** [cloudfoundry/gorouter#276]
As a follow up to issue #195, we have generated this [proposal](https://docs.google.com/document/d/1vcqlwchibRPnGn2pPQideaW8rmGMGoHFtgrS4RmsVl8/edit) to enable http2 in cloud foundry. 

We will be using this issue as our central coordination point and linking any associated PRs. Please let us know if you have requests or concerns.

cc @Gerg

**Comment by ameowlia** [comment]
Hi @MerricdeLauney ! 

Because of all the submodules and in order to keep things more organized, we ask that all issues for gorouter are opened on [routing-release](https://github.com/cloudfoundry/routing-release/issues).

❓ can you please move this issue there?
