### ISSUE TITLE
TraceID does not comply with the w3 Standard

### ISSUE THREAD

**Issue by rparadise** [cloudfoundry/gorouter#299]
https://github.com/cloudfoundry/gorouter/blob/a4fe6f37e0b2e22ae79a3b285126219a6f5dbf93/handlers/zipkin.go#L59

In the code, when a new traceID is created, it is assigned the spanID value. The spanID size is set to 8 Bytes

However, a W3 specification defines a 16-byte array format: https://www.w3.org/TR/trace-context/#trace-id

By not complying to the specification, the request trace can be broken. A solution that does comply to the standard may not consider the traceID created by the code and generate a new one that meet the requirements. 

I wanted to share my concern in this issue, and by the present request your comments.  If the issue makes sense, I would suggest to add a function to generate the traceID with a size of 16 Bytes.

Thanks

**Comment by mariash** [comment]
Fixed in this commit: https://github.com/cloudfoundry/gorouter/commit/e5d7aab0b68ed16f3ea36caa2a739e68dc5c2779
