### ISSUE TITLE
404, Requested route ('%s') does not exist.

### ISSUE THREAD

**Issue by mihai-cirstoiu** [cloudfoundry/gorouter#338]
This is not a bug report, just some feedback.
My services are deployed in PCF and if one of them is down then your service is the one who returns:

404 Not Found: Requested route ('....') does not exist.

I also want to use 404 in my services to tell if a certain resource was not found but I can't because the client can't tell the difference between service down (hence route not found) and resource not found. Don't tell me it should look at the body: is it text, does it contains Requested route... aha is down.

From client perspective is not gorouter who gets called, it's my service. From this reason I found a poor decision you took to return 404 when you could use 503, not to mention the response as a text.

**Comment by maxmoehl** [comment]
As per the [README](https://github.com/cloudfoundry/gorouter#reporting-issues-and-requesting-features), please open such issues against the [routing-release](https://github.com/cloudfoundry/routing-release) repository and not here.

Whenever gorouter encounters an error and returns a status code on its own the header `x-cf-routererror` is set. In the case of a unknown route the header will be set like this: `x-cf-routererror: unknown_route`. This should be enough for your client to distinguish between 404s from the application and  404s from gorouter.
