### ISSUE TITLE
GoRouter attempts to detect and set response "content-type" header if not set by server

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/gorouter#62]
It appears that the go router force sets the content-type header of a response if the originating server doesn't set one.  See test cases below.  I believe the router should not attempt to detect the content-type of the response and set a header if the server chose not to set a content-type.

We ran into this issue again when trying to deploy a third party application to cloud foundry.  In this situation the third party client is using Jquery.ajax to request content from the server.  Something with the way Jquery.ajax handles the response is modified if there is a content-type=text/xml response provided vs not.  This causes jquery to fail to parse the response the same way the application developers intended.

I know this could probably be logged as a bug against the third party application to be more explicit about response content-types.  However, I think again the CF router is not properly acting as a "transparent" proxy by inserting this header when not provided.  So, I submit an issue here as well.

Here are some test cases:

```
	It("Content-type is not set by proxy", func() {
		ln := registerHandler(r, "content-test", func(x *test_util.HttpConn) {
			_, err := http.ReadRequest(x.Reader)
			Ω(err).NotTo(HaveOccurred())

			resp := test_util.NewResponse(http.StatusOK)
			x.WriteResponse(resp)
			x.WriteLine("hello from server")
			x.Close()
		})
		defer ln.Close()

		x := dialProxy(proxyServer)

		req := x.NewRequest("GET", "/", nil)
		req.Host = "content-test"
		x.WriteRequest(req)

		resp, _ := x.ReadResponse()
		Ω(resp.Header.Get("content-type")).To(Equal(""))
	})
	
	It("Content-type xml is not set by proxy", func() {
		ln := registerHandler(r, "content-test", func(x *test_util.HttpConn) {
			_, err := http.ReadRequest(x.Reader)
			Ω(err).NotTo(HaveOccurred())

			resp := test_util.NewResponse(http.StatusOK)
			x.WriteResponse(resp)
			x.WriteLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
			x.Close()
		})
		defer ln.Close()

		x := dialProxy(proxyServer)

		req := x.NewRequest("GET", "/", nil)
		req.Host = "content-test"
		x.WriteRequest(req)

		resp, _ := x.ReadResponse()
		Ω(resp.Header.Get("content-type")).To(Equal(""))
	})
```

When running these tests I get the results:

```
  Expected
      <string>: text/plain; charset=utf-8
  to equal
      <string>:

  Expected
      <string>: text/xml; charset=utf-8
  to equal
      <string>: 
```

**Comment by shalako** [comment]
@youngm Gorouter has been upgraded to golang 1.5.3 in cf-release v230. Please let us know if it addresses this issue.

**Comment by youngm** [comment]
@shalako K, I'll get to it in a couple of weeks.  Thanks!

**Comment by shalako** [comment]
I believe I've validated this is fixed.

Added the following endpoint to dora in file dora.rb
https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/assets/dora/dora.rb

```
 get '/no-content-header/:headerName' do
    h = params[:headerName]
    response.headers[h] = ''
    "Hi, I'm Doraaaaaa! with empty #{h} Header"    
  end
```

curled the new endpoint `/no-content-header/Content-Type`
```
$ curl -v dora-scoen.superman.cf-app.com/no-content-header/Content-Type
* Adding handle: conn: 0x7f9b12004400
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7f9b12004400) send_pipe: 1, recv_pipe: 0
* About to connect() to dora-scoen.superman.cf-app.com port 80 (#0)
*   Trying 52.20.255.245...
* Connected to dora-scoen.superman.cf-app.com (52.20.255.245) port 80 (#0)
> GET /no-content-header/Content-Type HTTP/1.1
> User-Agent: curl/7.30.0
> Host: dora-scoen.superman.cf-app.com
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 49
< Content-Type:
< Date: Wed, 03 Feb 2016 23:17:14 GMT
* Server WEBrick/1.3.1 (Ruby/2.2.3/2015-08-18) is not blacklisted
< Server: WEBrick/1.3.1 (Ruby/2.2.3/2015-08-18)
< X-Cf-Requestid: 6637b165-0a9e-4868-419c-59a47f6423ab
<
* Connection #0 to host dora-scoen.superman.cf-app.com left intact
Hi, I'm Doraaaaaa! with empty Content-Type Header
```

Notice Content-Type is left empty. We did not test when Content-Type header is not present at all.

**Comment by shalako** [comment]
It appears that Gorouter must still be appending this header.

Used this bash script with the binary buildpack from the [Diego Inigo test suite](https://github.com/cloudfoundry-incubator/inigo/blob/master/fixtures/app_fixtures.go#L65-L91):
```
#!/bin/bash
set -e
index=${INSTANCE_INDEX}
echo "Hello World from index '${index}'"
server() {
	mkfifo request$1
	while true; do
		{
			read < request$1
			echo -n -e "HTTP/1.1 200 OK\r\n"
			echo -n -e "Content-Length: ${#index}\r\n\r\n"
			echo -n -e "${index}"
		} | nc -l 0.0.0.0 $1 > request$1;
	done
}
for port in $PORT; do
  server $port &
done
wait
```

I pushed it using the binary buildpack: `cf p bash-hello -b binary_buildpack -c './hello'`

When I curl the Diego Cell host and port, this header is not included
```
# curl -v 10.0.64.66:60010
* Rebuilt URL to: 10.0.64.66:60010/
* Hostname was NOT found in DNS cache
*   Trying 10.0.64.66...
* Connected to 10.0.64.66 (10.0.64.66) port 60010 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.0.64.66:60010
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 1
<
* Connection #0 to host 10.0.64.66 left intact
```

When I curl the Router, the header is returned
```
# curl -v 10.0.32.15/ -H "Host: bash-hello.superman.cf-app.com"
* Hostname was NOT found in DNS cache
*   Trying 10.0.32.15...
* Connected to 10.0.32.15 (10.0.32.15) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host: bash-hello.superman.cf-app.com
>
< HTTP/1.1 200 OK
< Content-Length: 1
< X-Cf-Requestid: 5af960c3-8ba0-401a-7a9f-71c693640099
< Date: Thu, 04 Feb 2016 20:15:36 GMT
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 10.0.32.15 left intact
```

I'll reopen this issue :(

**Comment by shalako** [comment]
Verified this is now fixed by bosh ssh'ing onto a vm in the network, and curling an app that logs request headers directly through the router.
`curl 10.0.80.15/config -H "Host: broker.superman.cf-app.com" -v`

Content-type header was not included. 

Closing; this should be in an upcoming cf-release (if not 231, then 232)

**Comment by shalako** [comment]
My test on Feb 22 was a false positive; I didn't use the same test as on Feb 4. Someone else reported the issue in #116. We've got a fix on the way.

**Comment by shalako** [comment]
Ok, now we've fixed the issue. Closing.

```
$ curl -v 10.0.32.15 -H "Host: bash-hello.superman.cf-app.com"
* Rebuilt URL to: 10.0.32.15/
* Hostname was NOT found in DNS cache
*   Trying 10.0.32.15...
* Connected to 10.0.32.15 (10.0.32.15) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> Host: bash-hello.superman.cf-app.com
>
< HTTP/1.1 200 OK
< Content-Length: 1
< X-Vcap-Request-Id: 6d29cdd7-959d-4455-49f5-474a6afc0fd2
< Date: Tue, 08 Mar 2016 01:47:58 GMT
<
* Connection #0 to host 10.0.32.15 left intact
```
