### ISSUE TITLE
JSON files get corrupted by the router

### ISSUE THREAD

**Issue by jdubois** [cloudfoundry/gorouter#64]
This is probably related to #62

When I get a .json file, it get corrupted, but renaming it to .js solves the problem. There is something (I'm suspecting the router) that tries to give it a content type, which is wrong.

For instance, I have my [internationalized files](https://github.com/jhipster/jhipster-sample-app/tree/master/src/main/webapp/i18n) in JSON, and I have to rename them or they all get corrupted.

As those are "normal" static files, this of course work on all other platforms (Heroku/OpenShift) or on my laptop.

**Comment by saturnism** [comment]
@jdubois should the mimetype be `application/json`?

**Comment by jdubois** [comment]
Not sure this is still relevant, this is 4 years old

**Comment by AlexandreCassagne** [comment]
@jdubois The mapping is still 

`mappings.add("json", MediaType.TEXT_HTML_VALUE + ";charset=" + StandardCharsets.UTF_8.name().toLowerCase());`

in WebConfigurer (Gateway). You said that you're not sure this is still relevant, but I am going to serve .json static files and was wondering if everyone agrees that it is safe to change this line to `application/json` instead?

I can propose a pull request to make this change.

**Comment by jdubois** [comment]
@AlexandreCassagne yes please do a PR on the JHipster project about this (you can mention me if you want). I'm pretty sure we can remove this by now.
