### ISSUE TITLE
NATS message "vcap.component.discover" without inbox stops further NATS processing by gorouter

### ISSUE THREAD

**Issue by ondrap** [cloudfoundry/gorouter#66]
When I send a message over NATS with subject "vcap.component.discover" using the 'publish' call (without specifying the inbox parameter), gorouter tries to answer with empty subject, which causes a protocol error:
```
[TRACE] MSG: [Processing Client msg: 1 vcap.component.discover  ]%!(EXTRA *server.client=127.0.0.1:59390 - cid:4)
[ERROR] 127.0.0.1:59389 - cid:3 - Error reading from client: processPub Parse Error: '185'
```
What the gorouter sent:
```
PUB  185
{"type":"Router","index":0,"host":"192.168.200.13:8082","credentials":["",""],"uuid":"0-8f0375e4-1fc1-4970-4217-6ee2ca375618","start":"2014-11-22 11:59:06 +0100","uptime":"0d:0h:0m:3s"}
```
From that moment gorouter does not respond to any NATS message and I get these messages hinting that NATS is not working: "State is stale; NOT pruning"

* the NATS API should not allow sending messages with empty subject
* gorouter should not reply to these messages
* even if all this happens, the connection to the NATS server should be simply restarted and everything should go on

**Comment by mmb** [comment]
Could you please test it again? And see if this problem still happen ? Could you tell me what is the formate of the NATS message? Could you tell us how to generate the discover message?

**Comment by ematpl** [comment]
I think something like `nats-pub vcap.component.discover -s nats://nats:nats@10.244.0.6:4222` using the `nats-pub` script from https://github.com/nats-io/ruby-nats will send the poison message. That command just worked for me against CF v214 on BOSH-lite. The gorouter logs indicate that its NATS client disconnected, but it seems to have reestablished the connection, as my routes are still up, and I can establish new routes.

cc @jfmyers9 :)

**Comment by shalako** [comment]
Verified this is fixed, and looks like it was shipped with cf-release v217.

The fix: https://github.com/cloudfoundry/gorouter/commit/13e364efb6e610d98840ad839a5dc505aaca2718
bump of gorouter in cf-release: 
https://github.com/cloudfoundry/cf-release/commit/a139290bb2efa04fe3f9fd5ad730c28e032dc031
