### ISSUE TITLE
Staleness interval not included in the router.start message

### ISSUE THREAD

**Issue by bondj** [cloudfoundry/gorouter#72]
The router.start message is documented as containing the amount of time a route is not updated for before it is considered stale.  Instead it contains the minimumRegisterInterval, which I guess is the maximum frequency updates should be sent to the router.

Both pieces of information are useful for new clients to discover the frequency of updates they need to send.

**Comment by jfmyers9** [comment]
Hi @bondj,

Thanks for bringing this to our attention. We agree that this is useful information to send on a `router.greet`/`router.start`, so we have gone ahead an added them to both messages. This should be resolved as of 1f64ba67fd0bcea4d8238682d03dea17e41922c7.

Thanks,

@jfmyers9, CF Runtime Team
