### ISSUE TITLE
README.md is out of date

### ISSUE THREAD

**Issue by bondj** [cloudfoundry/gorouter#73]
The contents of the route.register does not match the actual structure, and some description of PrivateInstanceId, StaleThresholdInSeconds and App would be useful.

The behaviour to send a new router.register when a router.start is received, so that it can synchronized across all gorouters needs to be documented

I've raised an earlier issue saying the router.start message does not contain the staleness value.  What is currently documented is not consistent with the current implementation.

**Comment by zaksoup** [comment]
Hi @bondj,

We updated the README to more accurately reflect the current state of the gorouter. Thanks for bringin' this to our attention.

Best,
@zaksoup && @jfmyers9, CF Runtime Team.
