### ISSUE TITLE
Sticky Sessions lost on App Failure

### ISSUE THREAD

**Issue by kelapure** [cloudfoundry/gorouter#76]
I’m working on a demo for Blue Green deployment using Redis for session sharing and I am running into what looks to be a bug in CF.  I have a simple app that just stores an Integer in Session, and increments on every hit. Under normal usage, everything works as expected; the session is stored in Redis under the key that is the value of the `JSESSIONID` cookie, and the `__VCAP_ID__` cookie keeps the requests returning to the same instance of the app. 
 
If I cf stop and cf start the app, the next request works as expected as well.  The browser sends the `JSESSIONID` to the fresh app instance, which doesn’t have the session, so it loads the session object from Redis, and increments the value properly.  The problem is the `__VCAP_ID__` cookie is pointing to a non-existing instance now, and it is never updated to the new ID of the instance that was just hit, so session stickiness is lost.  This causes requests to bounce among all instances in the cluster, and really screws the Redis session manager up (it only loads the session from Redis if the session does not exist in memory and not on every request, so you end up with an independent session on each app instance).
 
```It appears the only time the __VCAP_ID__ cookie is updated is when the JSESSIONID cookie is created.  If I go into the web developer plugin on my browser and delete my __VCAP_ID__ cookie but keep the JSESSIONID cookie there,  __VCAP_ID__ is never recreated and I bounce around all the instances.  If I manually delete my JSESSIONID cookie but leave the __VCAP_ID__ cookie, on the next request, a new JSESSIONID cookie is created along with a new __VCAP_ID__```.

 This issue leads to loss of session affinity when apps failover. Can this be fixed?

**Comment by dieucao** [comment]
@kelapure This sounds like a bug we currently have open in the backlog [1] that we'll be working on soon.  We'll update this issue when that bug has been fixed.

[1] https://www.pivotaltracker.com/story/show/79046748

**Comment by kelapure** [comment]
@dieucao Thanks for the prompt response!

**Comment by dieucao** [comment]
@kelapure This will be fixed in the next cf-release.
