### ISSUE TITLE
It does not compile

### ISSUE THREAD

**Issue by imarzi** [cloudfoundry/gorouter#77]
Hi!

I've tried to compile the code by following the instructions but it continues to give me this error:

/opt/src/github.com/cloudfoundry/gorouter/router/router.go:168: unknown "net/http".Server field 'ConnState' in struct literal

Could you please help with that?

Tnx

**Comment by crhino** [comment]
Hi @imarzi,

What is your GOPATH set to? It is also possible that you are compiling against the wrong version of go. Please use Go 1.4 at a minimum for the gorouter.

Let us know if that works and if you encounter any other problems!

@crhino + @zaksoup CF Runtime Team

**Comment by imarzi** [comment]
It worked. Thank you!
