### ISSUE TITLE
sticky session via urlparam

### ISSUE THREAD

**Issue by adrai** [cloudfoundry/gorouter#78]
What is your opinion on this topic?
https://github.com/Automattic/socket.io/issues/2036

**Comment by dieucao** [comment]
@adrai We don't like the idea of gorouter inspecting url parameters.
You might find our Route Services proposal [1] could fit your use case.
It's probably a few more months before we start work on that though.

[1] https://docs.google.com/document/d/1bGOQxiKkmaw6uaRWGd-sXpxL0Y28d3QihcluI15FiIA/edit?usp=sharing

**Comment by adrai** [comment]
Do you currently have an alternative solution to guarantee sticky connection for non-browser clients? (i.e. that uses socket.io)
At the moment I know no working scalable solution for non-browser clients that uses socket.io on cloud foundry.

PS. Why not with query param? Like HAProxy can do?

**Comment by dieucao** [comment]
@adrai I can't think of an alternative solution.
