### ISSUE TITLE
Error on installing gorouter

### ISSUE THREAD

**Issue by garagatyi** [cloudfoundry/gorouter#83]
I tried to do `go get -v github.com/cloudfoundry/gorouter` and got 
`# github.com/cloudfoundry/gorouter
/usr/local/go/src/github.com/cloudfoundry/gorouter/main.go:60: not enough arguments in call to cf_debug_server.Run`

Looks like it is because of https://github.com/cloudfoundry-incubator/cf-debug-server/commit/be657922f24da3d7f2c1c5a7699f6c3dfb9da457

**Comment by utako** [comment]
Hi @garagatyi,

Thanks for the notice. We will update the README so you do not see these errors. Gorouter itself should be fine as all of its dependencies are saved in godeps. If you run
```
go get -d github.com/cloudfoundry/gorouter
cd $GOPATH/src/github.com/cloudfoundry/gorouter
godep restore
``` 
and then follow the instructions for running tests everything should pass.

Thanks,
@utako && @DanLavine, The CF Runtime Team
