### ISSUE TITLE
"Browser driven" session stickyness

### ISSUE THREAD

**Issue by mpermar** [cloudfoundry/gorouter#89]
Hi guys, 

We recently ran into an interesting issue within a load test which made me thought about the possibility to support browser driven session stickyness. 

First off, we don't have browsers but rather a Java server using Apache's httpclient to interact with the CF application but for simplicity I've used the term browser. Basically, our issue is that within a load test our network infrastructure can get some severe contention. During that contention, our "browser" under some I/O errors will retry the http request a few times to prevent some of those temporary network glitches. On the other hand, our app instances when they get the first message for a given interaction they set session affinity with the jsessionid variable.

So, so far so good. But what we found during some load test runs is that if the first message that triggers session affinity is retried due to network contention sometimes it might end up in different application instances which causes a) multiple redundant responses getting to our Java server and b) undesirable state and behavior in N-1 app instances. 

So I thought that a possible approach to this would be to hint the CF router to enable session affinity without having to reach the app instance for it. That way, all those duplicate messages retried would end up in the same app instances where we already have mechanisms to prevent dupes. 

What do you guys think? Or perhaps there is a different way to sort out this type of scenario...

Thanks,
Martin

**Comment by crhino** [comment]
@mpermar Sorry for taking so long to reply. We have thought about making session affinity a less ad-hoc solution by somehow exposing an API through the cloud_controller perhaps, but no stories or proposals have been written yet.

In terms of a way to help you right now, I'm sorry to say that I can't think of any. The only way to ensure that only a single application sets the affinity flag would be to not have multiple initial requests in flight at once, which seems like a hard ask.

**Comment by mpermar** [comment]
Thanks for coming back @crhino. And yes a cloud_controller API or any way to tweak the default behaviour would suit. In the meantime we will have to either workaround it or leave with it. And indeed, the only solution that is not open to race conditions, complexity or decreased performance would be to skip these retries for the initial request. 

Thanks again,
Martin

**Comment by shalako** [comment]
@mpermar Do you imagine a client generating a session id and sending it in a cookie, then gorouter looking up whether it knows about that id already and if not making a load balancing decision and picking a backend instance? Then all subsequent requests with the same session id being routed to the same app instance? This would require shared state across the routers, otherwise each router will have its own mapping of client generated session ids to backends. We want to avoid shared state with strong consistency. Eventual consistency is ok, but I don't think that will satisfy the use case.

Clients could use the new `X-Cf-App-Instance` header to choose a backend, but this requires the client to know the app guid and to pick an app instance index.

**Comment by mpermar** [comment]
Thanks for the answer @shalako. I certainly imagine it because products like nginx or haproxy do support it. One stateless approach is to generate a hash from the client cookie value on the first request. Then use the hash value to choose the app instance id. The vcap cookie could be generated at that same moment and returned back by the sdk, or just generated on the response. Subsequent requests would use the vcap cookie for routing. 

Additionally consistent hashing algorithm (+ likely other approaches) can be used to make it more resilient to auto-scaling events while on multiple first-request retries.

**Comment by mpermar** [comment]
Adding to the above, the support does not need to be via a cookie. It could be a new X header like the one you pointed out, but the router can do a hash-based routing instead of hand picking an instance.

**Comment by shalako** [comment]
@mpermar Thank you for the clarifications. Although the feature is interesting, we cannot prioritize it yet as we have more pressing work to deliver. 

Would you be interested in contributing the feature?

**Comment by mpermar** [comment]
I wish I could. My golang skills are pretty much nil.

**Comment by shubhaat** [comment]
We don't plan to add support for this use case to gorouter, but we are considering alternatives to the sticky session use case in the Istio-based replacement subsystem we are working on now: https://docs.google.com/document/d/1LgLY0g39fzpg1_4zTckbH1mOuuSKGvYwp2tkakoe9ys/edit

As you'll find in the section titled "Features Subject to Change", we would like to enable an app developer to configure the platform to initiate sticky sessions for every client of a given application.  If you have additional feedback, please add a comment there. We have added this issue to our evidence for an alternative.
