### ISSUE TITLE
Affinity is not maintained properly with context paths

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/gorouter#90]
The current code no longer manages the affinities properly when context paths are in play.

If you have routes defined by separate context paths, the cookie generated should include the path that matched. The browser/client should choose the longest path match based on the set of available cookies.

There should be a different VCAP_ID remembered for a route on /, /a or /b if all 3 are defined for separate applications.

**Comment by crhino** [comment]
Should be fixed by: https://www.pivotaltracker.com/story/show/98068176
