### ISSUE TITLE
How can I proxy a request to a specifically instance, X-CF-InstanceID seems not work.

### ISSUE THREAD

**Issue by Liuyanglong** [cloudfoundry/gorouter#91]
Need help！
 when I use gorouter as router tool, I have 4 instances for a app, but now I want proxy some request to a specifically instance, I can not find the solution。
I try to use "X-CF-InstanceID" in request Header, but it does not work.
e.g : 
```
curl -i -H "Host: test.app.com" -H "X-CF-InstanceID: 111111"  go-router:8081/       
```
Need Help~~~

registry instance msg 1：
```
{
"host":"172.16.5.44",
"port":49388,
"uris":[
"test.app.com"
],
"app":"test.app.com",
"private_instance_id":"111111"
}
```

registry instance msg 2：
```
{
"host":"172.16.5.44",
"port":49389,
"uris":[
"test.app.com"
],
"app":"test.app.com",
"private_instance_id":"222222"
}
```

registry instance msg 3：
```
{
"host":"172.16.5.44",
"port":49390,
"uris":[
"test.app.com"
],
"app":"test.app.com",
"private_instance_id":"333333"
}
```

registry instance msg 4：
```
{
"host":"172.16.5.44",
"port":49391,
"uris":[
"test.app.com"
],
"app":"test.app.com",
"private_instance_id":"444444"
}
```

**Comment by crhino** [comment]
Hi @Liuyanglong,

Sorry for taking so long to reply, we had a lot of people on vacation this last week.

In general, the GoRouter does not allow you to pick a specific instance to send a request too. It does support sticky sessions in a roundabout way. By [registering a private instance id](https://github.com/cloudfoundry/gorouter/blob/9aa96e52d61a2c6874299a04db6947ac39a82895/proxy/proxy.go#L227-L230) and setting the `JSESSIONID` cookie on the first response, the GoRouter will set a value that enables it to route it back to the same application instance. The first response will always be routed to a random backend currently though.

Let me know if you have any more questions!

**Comment by shalako** [comment]
We'll mark this issue as solved. Feel free to re-open if we haven't answered your question.
