### ISSUE TITLE
routing-api 

### ISSUE THREAD

**Issue by jianghaitao** [cloudfoundry/gorouter#94]
We used bosh to deploy Cloud Foundry on top of Openstack and having some issues with gorouter configuration. It is currently has following lines about routing-api:
```
routing_api:
  uri: http://routing-api.<router public ip>.xip.io
  port: 3000
```
Above doesn't seems to be right since router has no idea what routing-api.<router public ip>.xip.io is. I dumped out the routes the gorouter knows, it has uaa.<router public ip>.xip.io  and others, but no routing-api.<router public ip>.xip.io 

How should we set this?

Thanks a lot in advance.

**Comment by jianghaitao** [comment]
Update:
I changed the gorouter.yml file to point to the router directly:
```
routing_api:
  uri: http://<router ip>
  port: 8080
```
Now I get following 401 error in the gorouter.log:
```
{"timestamp":1441751750.614469290,"process_id":9333,"source":"router.route_fetcher","log_level":"error","message":"bad response from event source: 401 Unauthorized","data":null}
```
I can curl http://<gorouter>:<secret>@<gorouter ip>:8080/routes without any issue.

Still the question remains: how should we configure the routing_api?

**Comment by crhino** [comment]
@jianghaitao The routing_api is another component of Cloud Foundry that we have been developing. [The proposal can be found here](https://docs.google.com/document/d/1iSrqmjRDEM0y_nIgk-iXNR9P-ODV7E-StN4UMj8y0lQ/edit#heading=h.4k2cr6pdcze8) and [the repo here](https://github.com/cloudfoundry-incubator/routing-api).

It is still in experimental stages, and is not recommended for anyone to be using it currently. I am not sure what you are trying to achieve, but I would recommend that you set the [enable_routing_api property](https://github.com/cloudfoundry/cf-release/blob/develop/jobs/gorouter/spec#L46) to false. The GoRouter will still work without it.

**Comment by crhino** [comment]
To be more clear, the routing_api uri is set [here for the GoRouter](https://github.com/cloudfoundry/cf-release/blob/develop/jobs/gorouter/templates/gorouter.yml.erb#L54), which you need consul deployed for it to work correctly.

**Comment by markstgodard** [comment]
Hi @jianghaitao 

Given that the routing-api is still considered experimental and subject to change, we'd suggest you stick with the gorouter / cf-release defaults for now. And feel free to follow the cf-release / cf-dev mailing list for updates / announcements related to routing-api. 
Thanks!
Mark - CF Routing Team
