### ISSUE TITLE
404 when query parameters are present on a context path based route

### ISSUE THREAD

**Issue by caseyhadden** [cloudfoundry/gorouter#95]
We've been exploring usage of the new context path based routing feature. In general, it has worked very well. We have come upon one problem case. When we create a route such as 'my_path', and then issue a request that includes query parameters, we receive a 404. For example, GET /my_path?foo=bar will fail when my_path is registered and GET /my_path succeeds. You can see the failure with a test such as:

```go
	It("Handles requests with a query string on path", func() {
		ln := registerHandler(r, "test/my_path", func(conn *test_util.HttpConn) {
			conn.CheckLine("GET /my_path?foo=bar HTTP/1.1")

			conn.WriteResponse(test_util.NewResponse(http.StatusOK))
		})
		defer ln.Close()

		conn := dialProxy(proxyServer)

		conn.WriteLines([]string{
			"GET /my_path?foo=bar HTTP/1.1",
			"Host: test",
		})

		conn.CheckLine("HTTP/1.1 200 OK")
	})
```

Our expectation is that such a request would resolve the correct application for my_path with the query parameters passed along. We are seeing this behavior on cf-release v214, though the above test fails against the master gorouter branch.

I have created [one possible fix](https://github.com/caseyhadden/gorouter/commit/f17a500c27ef96acae6ff1b9ff7fbbd3087ceb3b) by stripping the query string from request.RequestURI. It looks like Go 1.5 might have a more succinct method via request.URL.EscapedPath(), but it was unclear to me whether Go 1.5 was allowed and the travis.yml suggested it might not be.

I'm happy to turn that commit into a pull request if desired.

Thanks.
Casey

**Comment by markstgodard** [comment]
Hi @caseyhadden 

Thanks for the find! 
Took a quick look at it and yes definitely a defect. Your proposed fix would fix the issue,  however when reviewing the Issue and on closer inspection,  I found a fix closer to the route registry.  Basically wanted to put the fix closer to the root problem (vs. in the proxy).

Should have a fix up pretty soon, and you can have a look.

Cheers

@markstgodard (from the CF Routing Team)

**Comment by caseyhadden** [comment]
Thanks, @markstgodard. I'd considered whether a fix somewhere lower might be a better fix, but wasn't sure about the total set of relationships among the pieces. Regardless, it will be good to get it fixed and working.

**Comment by shalako** [comment]
Verified fixed with bosh-lite.

Fixed with commit https://github.com/cloudfoundry/gorouter/commit/8365ea68c0ae49b6ced420b1054cd9910eba4f42

Gorouter bumped in cf-release https://github.com/cloudfoundry/cf-release/commit/408ea1ac3d6ddc0b01ba9315a82a58e1589b7e92

The bump hasn't made it to master yet, so is likely to be included in v218
