### ISSUE TITLE
sticky session key cookie __VCAP_ID_ doesn't re-use "Secure" attribute of session cookie

### ISSUE THREAD

**Issue by shawnzhu** [cloudfoundry/gorouter#99]
it uses `maxAge` and `Path` of session cookie named `JSESSIONID` in `__VCAP_ID_` cookie, but not the `Secure` attribute. see func [`setupStickySession`](https://github.com/cloudfoundry/gorouter/blob/master/proxy/proxy.go#L344-L377)

## Expected result
`__VCAP_ID_` cookie should as secure as `JSESSIONID` cookie.

## Actual result
it lacks of `Secure` attribute for `__VCAP_ID_` cookie when `JSESSIONID` cookie has `Secure` attribute.

**Comment by fraenkel** [comment]
And what happens if you choose not to use https? http is still an option.

**Comment by shawnzhu** [comment]
@fraenkel yes, my point is it should use `Secure` attribute of `JSESSIONID` cookie in `__VCAP_ID_` cookie, just like `maxAge` and `Path`. if session cookie id is secure, session cookie id key should be secure as well.

**Comment by shalako** [comment]
hello @shawnzhu, thank you for your interest in gorouter.

Do you mean that if backend returns a cookie with `JSESSIONID` and `Secure`, Gorouter should return `Secure` in a cookie along with `VCAP_ID`?

If app returns a cookie with the secure attribute, but request is over http, the secure cookie will be exposed. Should we rely on apps to detect `X-cf-forwarded-proto` and return a secure cookie or not?

**Comment by shawnzhu** [comment]
> Do you mean that if backend returns a cookie with JSESSIONID and Secure, Gorouter should return Secure in a cookie along with VCAP_ID?

yes.

> If app returns a cookie with the secure attribute, but request is over http, the secure cookie will be exposed. Should we rely on apps to detect X-cf-forwarded-proto and return a secure cookie or not?

There're three cases when  `JSESSIONID` is secure plus request is over http:

1. keep `__VCAP_ID_` cookie without secure attribute. user agent will send it back but no `JSESSIONID` cookie over http, no need to stick request to specific instance. 
1. keep `__VCAP_ID_` cookie secure. Once user agent chooses secured channel like https, it will send both cookies.
1. stop sending out `__VCAP_ID_` cookie because it has no need to stick to an inexistent session (user agent will not send `JSESSIONID` cookie back over http)

I vote for 3) if you don't want to expose internal information over http.

**Comment by markstgodard** [comment]
Makes sense to set the `Secure` attribute based on the `JSESSIONID` cookie.

One caveat would be related to the `router.secure_cookies` deployment setting, which is what we are currently setting `VCAP_ID` secure setting to.  Assuming if `router.secure_cookies` is `true` we would override whatever the session cookie secure setting was?

Also @shalako we can discuss how we would like to handle cases where initial cookie creation is over http. Seems like right now, even if we set `router.secure_cookies` to true,  we don't do any sort of checks if the transport was over TLS.

**Comment by shalako** [comment]
@shawnzhu We believe the current behavior is as follows: 
- The secure property for the `VCAP_ID` cookie is always set based on the manifest property `router.secure_cookies`. If `router.secure_cookies: false`, `secure` is always false. If `router.secure_cookies: true`, `secure` is always true.

We are considering are considering a change to the behavior of this manifest property: 
- When `router.secure_cookies: false`, `secure` property for `VCAP_ID` cookie will match the  `secure` property for `JSESSIONID` cookie. 
- When `router.secure_cookies: true`, `secure` property for `VCAP_ID` cookie will always be true.

**Comment by markstgodard** [comment]
This feature is in cf-release v227+,  
https://github.com/cloudfoundry/cf-release/releases/tag/v227#routing

I'll get @shalako to close this issue.

Cheers
